### ISSUE TITLE
FIXME app crash with SSLError when system proxy had been set

### ISSUE THREAD

**Issue by kn007** [RimSort/RimSort#100]
if setting system proxy(even the proxy service is fine), it will fail.
working fine without system proxy

maybe using urllib3<=1.25.11 to fix it

```
Traceback (most recent call last):
  File "C:\DATA\tools\RimSort\urllib3\connectionpool.py", line 700, in urlopen
  File "C:\DATA\tools\RimSort\urllib3\connectionpool.py", line 996, in _prepare_proxy
  File "C:\DATA\tools\RimSort\urllib3\connection.py", line 369, in connect
  File "C:\DATA\tools\RimSort\urllib3\connection.py", line 504, in _connect_tls_proxy
  File "C:\DATA\tools\RimSort\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "C:\DATA\tools\RimSort\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "C:\DATA\tools\RimSort\ssl.py", line 500, in wrap_socket
  File "C:\DATA\tools\RimSort\ssl.py", line 1040, in _create
  File "C:\DATA\tools\RimSort\ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DATA\tools\RimSort\requests\adapters.py", line 489, in send
  File "C:\DATA\tools\RimSort\urllib3\connectionpool.py", line 787, in urlopen
  File "C:\DATA\tools\RimSort\urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/RimSort/RimSort/releases/latest (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DATA\tools\RimSort\view\main_content_panel.py", line 829, in actions_slot
  File "C:\DATA\tools\RimSort\view\main_content_panel.py", line 982, in _do_check_for_update
  File "C:\DATA\tools\RimSort\requests\api.py", line 73, in get
  File "C:\DATA\tools\RimSort\requests\api.py", line 59, in request
  File "C:\DATA\tools\RimSort\requests\sessions.py", line 587, in request
  File "C:\DATA\tools\RimSort\requests\sessions.py", line 701, in send
  File "C:\DATA\tools\RimSort\requests\adapters.py", line 563, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/RimSort/RimSort/releases/latest (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
```

**Comment by kn007** [comment]
log: [RimSort_with_system_proxy.log](https://kn007.net/filecup/uploads/1e508e99b8d831af1e6bb5f839268957.log)

step:
1.setting system proxy on control panel : (like https://www.browserstack.com/local-testing/proxy-settings-for-local-testing-parameters)
2.open rimsort
3.click "Check for update"
4.program popup window tip crash(with ok, show detail button)
5.ok, program exit

show detail log in https://github.com/RimSort/RimSort/issues/100#issue-1749881572

**Comment by twstagg** [comment]
> log: [RimSort_with_system_proxy.log](https://kn007.net/filecup/uploads/1e508e99b8d831af1e6bb5f839268957.log)
> 
> step: 1.setting system proxy on control panel : (like https://www.browserstack.com/local-testing/proxy-settings-for-local-testing-parameters#controlPanelWindows) 2.open rimsort 3.click "Check for update" 4.program popup window tip crash(with ok, show detail button) 5.ok, program exit
> 
> show detail log in [#100 (comment)](https://github.com/RimSort/RimSort/issues/100#issue-1749881572)
> 
> https://www.google.com/search?q=urllib3%3D%3D+%221.25.11%22+Caused+by+SSLError%28SSLEOFError%288%2C+%27EOF+occurred+in+violation+of+protocol+%28_ssl.c%3A1129%29%27%29%29

Can you please share how you have this configured?

![image](https://github.com/RimSort/RimSort/assets/2766946/e8289588-56bc-4d0a-9e6a-2c566fda58bd)

**Comment by kn007** [comment]
![20230610105708](https://github.com/RimSort/RimSort/assets/6196903/50778930-70e2-4149-bfce-61d715e91fb6)
![20230610105721](https://github.com/RimSort/RimSort/assets/6196903/a4d6b161-0ace-49bc-8d0b-6c5c98123ddb)

**Comment by twstagg** [comment]
> ![20230610105708](https://user-images.githubusercontent.com/6196903/244843163-50778930-70e2-4149-bfce-61d715e91fb6.png) ![20230610105721](https://user-images.githubusercontent.com/6196903/244843167-a4d6b161-0ace-49bc-8d0b-6c5c98123ddb.png)
> 
> http/sock5 compatible

Are you able to test running RimSort from source to confirm whether or not it is a bug in urllib?

Python `requests` module should pick up the proxy from your system with that sort of configuration. I also cannot reproduce on Linux.

**Comment by kn007** [comment]
I don't have the corresponding environment.

Could you compile a version of urllib using 1.25.11 for me to test?

**Comment by twstagg** [comment]
> I don't have the corresponding environment.
> 
> Could you compile a version of urllib using 1.25.11 for me to test?

Please reference: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy

This is a configuration issue, and not a bug in `urllib3`

Your issue is that your proxy is not responding because your proxy only speaks HTTP and not HTTPS.

When I initially configured mine as you had configured yours in Windows, I was able to reproduce the issue. Then, when I modified it to not have HTTPS/FTP proxy set, I was able to do the update function through the proxy.

Example:

![image](https://github.com/RimSort/RimSort/assets/2766946/b12d88c6-1a16-42f9-b2e1-85b5645bdb4a)

**Comment by twstagg** [comment]
I will add UI elements to signify this when an error is received.

**Comment by kn007** [comment]
@twstagg hmm, ok.
 but the "use the same proxy server for all protocols" checkbox had been clicked

**Comment by kn007** [comment]
@twstagg I don't think this is right. let me record a video.

**Comment by twstagg** [comment]
@kn007 What software are you using to host the proxy? Can you elaborate more on how that proxy is configured?

**Comment by kn007** [comment]
@twstagg I'll upload a video soon.
Strangely though, when I uncheck that option, manually populate all the settings, it works abnormally.
When I finally rechecked this option (use the same proxy server for all protocols), it worked fine.

.............Might be Microsoft's fault

**Comment by kn007** [comment]
@twstagg This is my screen recording.
Finally somehow it worked fine.
Sorry, I should have tested more rigorously.

https://kn007.net/filecup/uploads/85284f3f1e8417f048ef5afdce99dc15.mkv

**Comment by twstagg** [comment]
> @twstagg I'll upload a video soon. Strangely though, when I uncheck that option, manually populate all the settings, it works abnormally. When I finally rechecked this option (use the same proxy server for all protocols), it worked fine.
> 
> .............Might be Microsoft's fault



> @twstagg This is my screen recording. Finally somehow it worked fine. Sorry, I should have tested more rigorously.
> 
> https://kn007.net/filecup/uploads/85284f3f1e8417f048ef5afdce99dc15.mkv

No worries! Glad to hear you got it working! Proxies are no fun sometimes :(
