### ISSUE TITLE
Implement mod names for missing or inactive dependencies

### ISSUE THREAD

**Issue by jefferyharrell** [RimSort/RimSort#139]
Refer to https://discord.com/channels/1120855389651599400/1120855390138142782/1141705924780769390 for the whole story. Salient points:

joseasoler: Mods have a `<displayName>` for their dependencies in their About file.

twsta: Not all mods use that.

CaptainArbitrary: It seems to me that the brute-force approach would be to read About.xml and pull the `<displayName>` from the list of dependencies if present, and if it's not present (is it allowed to be missing?) pull the `<packageId>`.

twsta: I can implement `<displayname>` support … But its not 80% of a solution because that assumption you make indicates that at least 80% of all mods do this. So what I propose is this, in relation to the actual tooltip … We just display the names of all variants found in steamdb … Also in that moddependencies tag … I can try to parse a publishedfileid if the `<steamWorkshopUrl>` tag is present

**Comment by LionelColaso** [comment]
closing since duplicate same issue already exists 
https://github.com/RimSort/RimSort/issues/89
