### ISSUE TITLE
Suggestion: Do not show a popup when running the latest version of RimSort

### ISSUE THREAD

**Issue by joseasoler** [RimSort/RimSort#140]
**Is your feature request related to a problem? Please describe.**

After launching the latest version of RimSort, this confirmation popup appears:

![image](https://github.com/RimSort/RimSort/assets/3092211/da93638c-db60-403e-82a7-f991547bc132)

I can't open RimSort and switch to something else. I need to wait to press OK in there, otherwise it will never carry on with the loading process.

**Describe the solution you'd like**
Ideally the popup should only appear when an action from the user is required. In this case the user does not need to take any action and thus the popup is not necessary.

**Comment by twstagg** [comment]
This is fixed on main branch and will be included in next release
