### ISSUE TITLE
Implement clickable links in QMessageBox dialogues

### ISSUE THREAD

**Issue by twstagg** [RimSort/RimSort#148]
**Is your feature request related to a problem? Please describe.**
Links are not clickable in QMessageBoxes

**Describe the solution you'd like**
* rich text support for model.dialogues
    * support for url embed
            * Yes we could add a link to the notification. If we can get this done then we can just add 2 links to the dialogue:
            * One could say "Open URL in browser" <a href=https://steamcommunity.com/sharedfiles/filedetails/?id=1847679158
            and one could say "Open URL in Steam" <a href=steam://url/CommunityFilePage/1847679158

**Comment by Chunnyluny** [comment]
See https://github.com/RimSort/RimSort/issues/141#issue-1857642420 where José mentions the rendering of HTML such as links, the issues seem related

**Comment by hk21702** [comment]
Honestly, I think this is already possible for most of the dialogs. They just need to have the flag to have rich text enabled. May be able to close this once some of the current PRs relating to dialogues are merged.
