### ISSUE TITLE
Implement performance improvements

### ISSUE THREAD

**Issue by jefferyharrell** [RimSort/RimSort#158]
**Describe the bug**
There's about a three-second delay between clicking the "Sort active mods" button and getting the results. This seems to be independent of the number of active mods.

**To Reproduce**
1. Clear the active mod list by clicking the "Clear active mods" button. Only Core and the DLCs (if installed) should be in the active mod list.
2. Click "Sort active mods."
3. Observe that it takes about three seconds (roughly) for the active mods list to populate.

**Expected behavior**
Sorting an essentially empty active mod list should take imperceptible time. Sorting a longer active mod list might take longer in proportion to the number of mods in the list, but an empty list should sort instantaneously.

**Please complete the following information:**
 - OS: Windows, macOS, Linux
 - RimSort version: 6bc03c2
 - Are you running from Python interpreter or from a compiled RimSort release? Compiled.

[RimSort.log](https://github.com/RimSort/RimSort/files/12491698/RimSort.log)

**Comment by twstagg** [comment]
I have a series of performance improvements that I am working on planning that should help address this. Unfortunately, this is going to involve doing all of the things I have previously spoken to you about with the way XML is parsed and how information from the overall cache is used in relation to these activities. I will comment here once this has been addressed.

**Comment by twstagg** [comment]
This should be significantly faster with the UUID changes I have made recently - closing issue.
