### ISSUE TITLE
FIXME: RimSort isn't picking up my mod's version information

### ISSUE THREAD

**Issue by jefferyharrell** [RimSort/RimSort#162]
This is in reference to this mod: https://steamcommunity.com/sharedfiles/filedetails/?id=3027381000. RimSort says the mod version is "Not specified."

<img width="452" alt="image" src="https://github.com/RimSort/RimSort/assets/8659114/81f7fdd2-6234-4969-a735-55b100aa65fe">

Except it is so. This is the relevant part of my About.xml:

```xml
<ModMetaData>
  <packageId>CaptainArbitrary.CompactWorkTab</packageId>
  <name>Compact Work Tab</name>
  <author>CaptainArbitrary</author>
  <description>Adds vertical column labels and scroll-wheel support to make the Work tab a little more user-friendly.</description>
  <modVersion>1.1.2</modVersion>
  ...
```

**Comment by twstagg** [comment]
Fixed with #168
