### ISSUE TITLE
FIXME: Mac Intel build of Edge 6bc03c2 is broken (yes, that's the best I can do)

### ISSUE THREAD

**Issue by jefferyharrell** [RimSort/RimSort#167]
`RimSort-Edge_6bc03c2_Darwin_i386` cannot be run on macOS Ventura 13.5.2, either on Intel or on Apple Silicon through Rosetta 2. Trying to run the app results in this error message:

<img width="372" alt="image" src="https://github.com/RimSort/RimSort/assets/8659114/c7923956-197b-4bb4-8461-ee796731a400">

This message usually indicates that an app's code signature is incorrect, suggesting that the app has been modified since it was signed.

For details on the initial report, see https://discord.com/channels/1120855389651599400/1120864728210739311/1155955880861384794

**Comment by jefferyharrell** [comment]
Just confirmed that the issue is also present on macOS 10.

<img width="532" alt="image" src="https://github.com/RimSort/RimSort/assets/8659114/db1fd0e4-017e-4f65-81e5-adb740697afe">

**Comment by jefferyharrell** [comment]
And it doesn't matter which browser you use to download it, so it's not a quarantine malfunction. I think we're looking at a malfunction in the build pipeline somewhere.

<img width="532" alt="image" src="https://github.com/RimSort/RimSort/assets/8659114/4b18aa77-0df8-4a17-a2e7-59ca17cce99b">

**Comment by Ant-V** [comment]
It's not a bug, it's a common response of the OS on not signed applications.
Top overcome: 
Make sure in system preferences/settings, in Security and Privacy, in "allow application from:" "everyone" (if it exists, it is removed in later os versions) or at least "App Stores and identified developers"
Then to have it run, on the app, right click and select open. A different pop-up will appear that also includes the option to "open".
After that you will be able to launch the app normally

**Comment by jefferyharrell** [comment]
Unsigned apps are a separate issue — literally, see #159. This isn't an unsigned-app problem. I'm very grateful for the comment though, thanks very much!

**Comment by twstagg** [comment]
@jefferyharrell I don't have that issue when running on my Ventura VM:

![image](https://github.com/RimSort/RimSort/assets/2766946/0d0c8e11-9e8b-4805-8ef9-290417ed40e0)

Nor does the problem arise when I run it on the VM that I built it with (my Mojave VM)

**Comment by twstagg** [comment]
Reference: https://github.com/RimSort/RimSort/wiki/User-Guide#macos
