### ISSUE TITLE
Questions about the implementation of Steam mods

### ISSUE THREAD

**Issue by Ant-V** [RimSort/RimSort#173]
Setup: macOS, gog version Rimworld, no steam installed, mods downloaded online or via steamCMD before RimSort (as such all mods are in `RW.app/mods`)

### §1 Weird behavior with Inactive/Active list ###

1. If I only enter the Local Mods dir in settings, almost no steamCMD downloaded mod appears in inactive, (but they do appear in active)
2. If I set the Steam Mods dir to the same as local, everything appears, but the icons in active all show as local mods. 
(The extra mods show with the blue steam icon, not the purple cloud)
3. If I only set the Steam Mods dir to the local dir, only the mods in case 1 show, but now the all appear with the steam icon, instead of the local
4. In cases 1 & 2 mods no mod with local icon shows the extra "Workshop Options" on right click. In case 3, which shows the same mods as case 1, it shows the extra option but only on mods downloaded with steamCMD.

Is any of the above behavior expected? 

### §2 Update Workshop Mods ###

1. Any mod that appears here appears to be downloaded from Steam directly, not from SteamCMD
2. If I use the settings outlined in §1.1, no mods are shown
3. If I use the settings outlined in §1.2, only mods that were not listed in §1.1 are shown
4. If I use §1.3, which shows the same list of mods as §1.1, mods do appear

I have no real question about this, as it (probably?) stems from the above issues, but I felt like I had to mention those.
When I messed with the project so that it always shows SteamCMD instead of Steam, it proceeds, which brings me to the next question block

### §3 Downloading with SteamCMD in-app ###

SteamCMD does not download to the user set location, instead it downloads into `~/Library/application/steamapps/workshop/content/294100` and just leaves it there...
It looks like a combination of an oversight and a bug, because wherever the `steamcmd_wrapper` is called, it only gets passed its `steamcmd_install_path` and inside the wrapper it says it downloads it there, yet my `steamcmd_install_path` settings is set to be inside`~/Library/Application Support/RimSort`.
(It would also be better if RimSort could detect that I already have steamCMD installed and available as a simple command, in my /bin/ but that nitpicking is for another time and probably a future, different pull request)

In any case any download it does, due to it getting downloaded in the aforementioned dir, does not appear in the mod list.

Shouldn't it move the download to one of the set paths?

**Comment by twstagg** [comment]
> Setup: macOS, gog version Rimworld, no steam installed, mods downloaded online or via steamCMD before RimSort (as such all mods are in `RW.app/mods`)
> ### §1 Weird behavior with Inactive/Active list
> 
>     1. If I only enter the Local Mods dir in settings, almost no steamCMD downloaded mod appears in inactive, (but they do appear in active)
>
>     2. If I set the Steam Mods dir to the same as local, everything appears, but the icons in active all show as local mods.
>        (The extra mods show with the blue steam icon, not the purple cloud)
> 
>     3. If I only set the Steam Mods dir to the local dir, only the mods in case 1 show, but now the all appear with the steam icon, instead of the local
> 
>     4. In cases 1 & 2 mods no mod with local icon shows the extra "Workshop Options" on right click. In case 3, which shows the same mods as case 1, it shows the extra option but only on mods downloaded with steamCMD.
> 
> 
> Is any of the above behavior expected?

No, none of the above behavior is expected. Here are some things i believe you are missing in this:

1. Steam folder is only an option to be used with the directory that is created by an actual Steam client when a user subscribes/unsubscribes to/from a mod. As a GOG user, at this time, you should leave that folder path unconfigured.
2. A SteamCMD mod is a "local mod" that is downloaded by SteamCMD. The way that this works is that when you click the "Setup SteamCMD" button, it will actually symlink the SteamCMD directory to your RimWorld local mods directory. This step requires user configuration, which can be done by clicking "Setup SteamCMD".
3. You can configure your SteamCMD prefix (which defaults to RimSort storage dir) by right-clicking the "Setup SteamCMD" button at this time. This decides where the SteamCMD that RimSort uses gets installed. This is also where the Symlink to your RimWorld local mods dir will be created.

> ### §2 Update Workshop Mods
> 
>     1. Any mod that appears here appears to be downloaded from Steam directly, not from SteamCMD
> 
>     2. If I use the settings outlined in §1.1, no mods are shown
> 
>     3. If I use the settings outlined in §1.2, only mods that were not listed in §1.1 are shown
> 
>     4. If I use §1.3, which shows the same list of mods as §1.1, mods do appear
> 
> 
> I have no real question about this, as it (probably?) stems from the above issues, but I felt like I had to mention those. When I messed with the project so that it always shows SteamCMD instead of Steam, it proceeds, which brings me to the next question block

It does in fact stem from the above issues.

> ### §3 Downloading with SteamCMD in-app
> 
> SteamCMD does not download to the user set location, instead it downloads into `~/Library/application/steamapps/workshop/content/294100` and just leaves it there... It looks like a combination of an oversight and a bug, because wherever the `steamcmd_wrapper` is called, it only gets passed its `steamcmd_install_path` and inside the wrapper it says it downloads it there, yet my `steamcmd_install_path` settings is set to be inside`~/Library/Application Support/RimSort`. (It would also be better if RimSort could detect that I already have steamCMD installed and available as a simple command, in my /bin/ but that nitpicking is for another time and probably a future, different pull request)
> 
> In any case any download it does, due to it getting downloaded in the aforementioned dir, does not appear in the mod list.
> 
> Shouldn't it move the download to one of the set paths?

After my feedback in #1, this should hopefully be resolved. Let me know if not.

**Comment by Ant-V** [comment]
Ok, so resetting my symlink did fix the issue with the download location, but I still only see a fraction of my mods when I do not also add the Steam Mod dir pointing to the same as my local mods.

Also I see that with the current implementation you keep the names of the mods as their id, whereas all my other steamCli downloaded mods I (obsessively one might say) rename to the package id.
Renaming the folder to keep my naming scheme does make the mod look like a "local" instead of a "steamcmd" mod.

Where/how do you do the separation?

**Comment by twstagg** [comment]
> Ok, so resetting my symlink did fix the issue with the download location, but I still only see a fraction of my mods when I do not also add the Steam Mod dir pointing to the same as my local mods. ¹
> 
> Also I see that with the current implementation you keep the names of the mods as their id, whereas all my other steamCli downloaded mods I (obsessively one might say) rename to the package id. Renaming the folder to keep my naming scheme does make the mod look like a "local" instead of a "steamcmd" mod.
> 
> Where/how do you do the separation (in code)?
> 
> ¹ Edit: so, I only now realized that indeed the number of mods showing with only one path is correct, and when I add both paths it simply double counts them all, so only the mystery of why it shows them as not steam mods remains
> 
> Edit 2: Ok, found that: [util/mods.py#1346](https://github.com/RimSort/RimSort/blob/main/util/mods.py#L1346C82-L1346C82) changed it into `if metadata.get("folder") in (metadata.get("publishedfileid"), metadata.get("packageid")):` and works like a charm. Now my question is should I change the steamCMD implementation so that it works with a temporary folder or a different, fixed folder, instead of adding a symlink (which imho is a more robust solution), renames and then moves the files upon each download, or is that something that does not conform to the project's goals and design?

As you have pointed out - this naming of the mod folder by using it's Steam Workshop PublishedFileID is how we differentiate those mods downloaded via SteamCMD vs other mods that are just local mods. In fact, when you use the context-menu options to "convert" a mod to/from local/SteamCMD, you will see that all it does is rename those directories accordingly (via mod name or via publishedfileid)

We do not want to check the folder name against the packageID, as that is not the intent of the code that is executing here.

**Comment by Ant-V** [comment]
I do not see the option to convert a mod from local to steamCMD anywhere, if such an option exists, that would solve the issue as well.

In general I do not think that looking at a folders name especially in a local environment is a good idea, as (imo) the concept of a local environment is that you mess with it, which is also why I do not enjoy having a symlink to there and why I find it immensely more helpful to have the dirs named with their package id which is somewhat human readable unlike the arbitrary number of publishedfileid.

It is of course a design decision and as such I can totally respect that.

**Comment by twstagg** [comment]
> I do not see the option to convert a mod from local to SteamCMD anywhere, if such an option exists, that would solve the issue as well.
> 

[Screencast from 2023-10-02 18-20-00.webm](https://github.com/RimSort/RimSort/assets/2766946/b3b286c5-1822-49ae-b1f3-4eb9eda34e18)

The above is the option to convert from SteamCMD -> Local. Likewise, if the conditions are correct, then you will see an option to convert a Local mod to a SteamCMD mod. See the implementation of these options: https://github.com/RimSort/RimSort/blob/main/model/mod_list.py#L538-L609

Technically, a SteamCMD mod IS a Local mod. But we further differentiate SteamCMD mods from Local mods for functional reasons. A SteamCMD mod is a Local mod which has a PublishedFileID parsed that also has a folder name that is it's PublishedFileID (this is the way that SteamCMD downloads mods)

See how PublishedFileID is parsed: https://github.com/RimSort/RimSort/blob/main/util/mods.py#L1015-L1049

> In general I do not think that looking at a folders name especially in a local environment is a good idea, as (imo) the concept of a local environment is that you mess with it, which is also why I do not enjoy having a symlink to there and why I find it immensely more helpful to have the dirs named with their package id which is somewhat human readable unlike the arbitrary number of publishedfileid.
> 
> It is of course a design decision and as such I can totally respect that.

It is not necessarily a voluntary design decision :laughing: - the RimWorld game by default only loads mods from 3 places: 

1. The expansions directory, as those are technically loaded like any other mod.
2. The local mods directory, which is always right next to the game execuatble by default.
3. The Steam Workshop directory, if you are using Steam version of the game. I believe that is exclusive only to the Steam version of the game, but cannot confirm as I have not used G.O.G. release. I believe this because the "steam mod" support in the game has some integration with the Steamworks API.

Because of this limitation, this is why SteamCMD mods have to go in the Local mods directory. The symlink is required to do this, as when you use SteamCMD, the "prefix" that you can pass to it to force the install directory, will always have the traditional `steamapps/workshop/content/APPID` structure suffixed to the path you provide. RimPy does it in a similar way as us, in the sense that it "containerizes" the SteamCMD install, and then supports symlinking the `STEAMCMD_PREFIX/steamapps/workshop/content/294100` directory to your local mods. The reason for this choice in design is due to the above.

Reference: https://github.com/RimSort/RimSort/blob/main/util/steam/steamcmd/wrapper.py#L82-L88

On a side note, I have thought about making a RimWorld mod to support loading mods from additional configurable directories. Just another thing to do...

**Comment by twstagg** [comment]
Closing issue

**Comment by Ant-V** [comment]
You are correct, but you can have steamCMD download wherever (in my case, also rename them to the packageID, so I do not ~lose my sanity~ open a mod manager everytime I have to find a mod) and then move the mods in the local dir.

You can even use the temp dir with `tempfile.gettempdir()` and either setting the `env HOME` variable to someplace in there (Mac & Linux) or run `steamCMD.exe` from there (Windows). 

As said before though, it is absolutely a design decision. 
Not to mention that running a batch renamer to and from publishedfileid and packageid is zero effort.

Although I must say the option to convert cmd to local and back, does not appear for me, but I have not had the time to dig deeper and see if perhaps I am only missing something.
