### ISSUE TITLE
Implement preview images for all platforms on the User Guide landing page

### ISSUE THREAD

**Issue by Chunnyluny** [RimSort/RimSort#184]
**Is your feature request related to a problem? Please describe.**

> This is not exactly a problem, but the readme contains only a preview how the mac/Linux version looks like and not from windows, because I think there are more Windows users and people like to know how it looks for their Windows pc.

**Describe the solution you'd like**
> Windows preview gets added in the wiki or readme which I sent through this issue, I could do a pull request but I don't know where it will fit best.

**Describe alternatives you've considered**
> Add the window screenshot I Attached to this issue.

**Additional context**
> See image below

![image](https://github.com/RimSort/RimSort/assets/102756485/640e0707-b467-4bd2-a699-f3fdcc73f684)

**Comment by twstagg** [comment]
There really only needs to be one preview image in the README

However, if we would like to make platform-specific previews, we could list them under each platform's respective section in the User Guide here:

https://github.com/RimSort/RimSort/wiki/User-Guide#windows
https://github.com/RimSort/RimSort/wiki/User-Guide#macos
https://github.com/RimSort/RimSort/wiki/User-Guide#linux

That being said, the preview image in the README should be updated accordingly from time-to-time. It doesn't really matter what platform is there, considering the application is pretty much identical for all platforms.
