### ISSUE TITLE
FIXME: Crash on 1.0.6.2-hf on MacOS, AttributeError: 'MainContent' object has no attribute 'internal_local_metadata'

### ISSUE THREAD

**Issue by Trannosaur** [RimSort/RimSort#208]
I launch the executable (.app), and RimSort opens - it will then say I already have the latest version, I click okay.

At this point, An error dialog appears but with no text, just two buttons "Show Details..." and "OK", if I hit OK, the dialog will disappear and the app will crash completely in about 2 seconds. If I hit show details, I am shown this error:

Traceback (most recent call last):
  File "/Applications/RimSort.app/Contents/MacOS/RimSort.py", line 253, in main_thread
  File "/Applications/RimSort.app/Contents/MacOS/RimSort.py", line 180, in __initialize_content
  File "/Applications/RimSort.app/Contents/MacOS/view/main_content_panel.py", line 1291, in _do_refresh
  File "/Applications/RimSort.app/Contents/MacOS/view/main_content_panel.py", line 498, in __refresh_cache_calculations
  File "/Applications/RimSort.app/Contents/MacOS/view/main_content_panel.py", line 549, in _refresh_external_metadata
AttributeError: 'MainContent' object has no attribute 'internal_local_metadata'

**To Reproduce**
1. I just launch RimSort.app, it wasn't doing this behaviour initially - I'm not sure what changed.

**Expected behavior**
To be shown the RimSort main UI and see all of the fun animations as it handles the metadata etc.

**Screenshots**
<img width="1022" alt="Screenshot 2023-11-01 at 23 38 22" src="https://github.com/RimSort/RimSort/assets/291144/6d2e9490-a039-4989-a98f-b96011911660">

**Please complete the following information:**
 - OS: MacOS Sonoma, 14.0
 - RimSort version: 1.0.6.2-hf
 - Please provide a `RimSort.log`: I am unable to find documentation on where to find such a log.
 - Are you running from Python interpreter or from a compiled RimSort release? Compiled release.

**Additional context**

**Comment by twstagg** [comment]
This has been fixed in the Edge track. It will also be included in the next formal Alpha release.

To workaround this if you want to hang back - change the lines in your settings.json to not be "RimPy Mod Manager Database" and don't use that preset. I forgot to remove it in the release you are using.
