### ISSUE TITLE
FIXME: App self-modification fails due to app translocation on the Mac

### ISSUE THREAD

**Issue by jefferyharrell** [RimSort/RimSort#231]
**Describe the bug**
RimSort wants to save the state of the debug setting by modifying itself (creating or deleting a file inside the app bundle), but this is not allowed by Apple's app translocation mechanism, so the app crashes.

**To Reproduce**
1. Download RimSort as a ZIP file and extract its contents into the Downloads folder.
2. Without moving it to another folder, run the app.
3. Open the Settings dialog, then close it by clicking "OK".
4. The following exception is thrown:

<img width="632" alt="image" src="https://github.com/RimSort/RimSort/assets/8659114/80402e11-2e08-470e-9c2c-a79cde7e8fa1">

**Expected behavior**
The app should be able to run without error from the Downloads folder.

**Please complete the following information:**
 - OS: macOS 12 or later

**Proposed fix:**
Relocate the `DEBUG` flag file to `~/Library/Application Support/RimSort`. That way it should be writable regardless of whether RimSort is being run through app translocation.

**Comment by twstagg** [comment]
A fix for this was included in f24000b090e8566a134a0f63535fddb76bef5431

An Edge build would probably be needed to confirm, but I just changed the AppInfo base path I was using to use the storage dir instead of the application dir
