### ISSUE TITLE
FIXME: RimSort switches to Steam Workshop mods after restarting or refreshing

### ISSUE THREAD

**Issue by joseasoler** [RimSort/RimSort#238]
**Describe the bug**

When a modlist contains git local mods that are also present as Steam Workshop mods and RimSort is restarted or mods are refreshed, it will change the modlist to use the Steam Workshop version instead. I am unsure if this issue is exclusive to git local mods, or if it affects all local mods.

**To Reproduce**

1. Launch RimSort
2. Create a modlist containing some git local mods.
3. Click on "Save mod list".
4. Close RimSort
5. Launch RimSort
6. The active modlist is changed. It is now using Steam Workshop mods for all git local mods that have one. Mods that are only available as git local mods remain the same. Check the screenshots below for an example.

Alternate steps to reproduce the behavior:
1. Launch RimSort
2. Create a modlist containing some git local mods.
3. Click on "Refresh mods".
4. The active modlist is changed. It is now using Steam Workshop mods for all git local mods that have one. Mods that are only available as git local mods remain the same. Check the screenshots below for an example.

**Expected behavior**

I expected my modlist to not be altered after launching RimSort.

**Screenshots**

Initial modlist:

![image](https://github.com/RimSort/RimSort/assets/3092211/10b4eeab-9955-46be-8a8b-5a999c3eb949)

Modlist after restarting RimSort:

![image](https://github.com/RimSort/RimSort/assets/3092211/2c2d2de3-1e42-4cfd-895b-de242704c5a3)

**Please complete the following information:**
 - OS: Linux
 - RimSort version: Edge ed62b63  
 - I am running a compiled RimSort release.
 - `RimSort.log` files of steps 1-4 and 5-6 can be found attached below. These logs have been taken for the first set of repro steps.

[RimSort_Steps_1_to_4.log](https://github.com/RimSort/RimSort/files/13538097/RimSort_Steps_1_to_4.log)
[RimSort_Steps_5_to_6.log](https://github.com/RimSort/RimSort/files/13538099/RimSort_Steps_5_to_6.log)

EDIT: Added missing "after" screenshot.

EDIT2: Added alternate repro steps.

**Comment by twstagg** [comment]
@joseasoler Could you please provide logs with DEBUG mode enabled?

**Comment by joseasoler** [comment]
@twstagg Here they are. The logs attached to this comment has been obtained on Windows 11.

[00_Creating_Modlist_With_Local_Git_Mods.log](https://github.com/RimSort/RimSort/files/13596891/00_Creating_Modlist_With_Local_Git_Mods.log)
[01_After_Restart_Local_Mods_Are_Replaced_With_Steam_versions.log](https://github.com/RimSort/RimSort/files/13596892/01_After_Restart_Local_Mods_Are_Replaced_With_Steam_versions.log)

**Comment by Limfjorden** [comment]
@twstagg I reproduced this issue on mac as well.
