### ISSUE TITLE
FIXME: Set a wrong config path, now application keeps crashing and I can't change the path anymore

### ISSUE THREAD

**Issue by Flohs** [RimSort/RimSort#239]
**Describe the bug**
I set a wrong config path, now application keeps crashing and I can't change the path anymore

**To Reproduce**
Used arm latest arm build. Ran application, using autodetect for the folders.
The config folder path was empty, so I just set it to the rimworld folder. Now the application keeps crashing and I can't change the path anymore.

**Expected behavior**
Capture the error with the wrong config path, so the application is not crashing, which allows me to change the folder.

**Screenshots**
<img width="1020" alt="image" src="https://github.com/RimSort/RimSort/assets/4445415/bfa0ee29-252f-4352-a3a3-352a82164689">

**Please complete the following information:**
 - OS: MacOS 14.1 (23B2073)
 - RimSort version: Alpha-v1.0.6.2-hf
 - Please provide a `RimSort.log`:
 Don't know where that log would be
 - Are you running from Python interpreter or from a compiled RimSort release?
 Compiled Release

**Comment by twstagg** [comment]
@Flohs 

Thanks for your report. The next Edge build will address this. Apologies as we are a bit behind on releasing that.

**Comment by twstagg** [comment]
I believe this issue has been fixed for awhile. Sorry for the delay in response.
