### ISSUE TITLE
FIXME: Updater deleted the /home/user folder on Linux

### ISSUE THREAD

**Issue by hideki2k02** [RimSort/RimSort#243]
**Describe the bug**
I'm not 1000% sure about this but during the process of updating my /home folder was entirely wiped and only the RimSort folder was left intact, could someone look into this? I'm not sure it was a fluke or some other app that went mad.

**To Reproduce**
1. Open [RimSort Alpha 1.0.6.2-hf](https://github.com/RimSort/RimSort/releases/tag/alpha-v1.0.6.2-hf)
2. Wait for it to check for updates
3. Update
4. The entire /home/user will be wiped but a lonely /home/user/RimSort folder will stand

**Expected behavior**
The Updater should've only deleted the previous RimSort files instead of the entire /home/user folder

**Please complete the following information:**
 - OS: Fedora Linux 39
 - RimSort version: alpha-v1.0.6.2-hf
 - Compiled RimSort release? 

**Additional context**
I was not doing anything else on the system that could've possibly delete the /home/user folder so i'm not entirely sure what could have caused it, maybe running it as sudo?

**Comment by Chunnyluny** [comment]
Can you please try the latest edge release, the release from August has some issues and the latest edge release from November might have them fixed?

**Comment by hideki2k02** [comment]
I've been using the latest Edge Release flawlessly (other than i had to reset the config file), since there are no updates i cant reproduce if this is a legitimate issue. But i guess its worth taking a look at the update script...

**Comment by hideki2k02** [comment]
It turns out the culprit was related to a .desktop entry i've had made, so beware in case you're still using an older version that has it. 

The fix is to set the Work Directory to the RimSort folder.

**Comment by twstagg** [comment]
Thanks for reporting. I am closing this as the old updater has been completely disabled. It will be rebuilt with something robust and completely failsafe.
