### ISSUE TITLE
FIXME: Crash on launch 

### ISSUE THREAD

**Issue by potatoo14** [RimSort/RimSort#245]
**Describe the bug**
Rimsort crashes silently on launch, [file with terminal output](https://github.com/RimSort/RimSort/files/13807899/crash.log).

**To Reproduce**
1. Try to open rimsort

**Expected behavior**
Rimsort should open.

**Please complete the following information:**
 - OS: Arch Linux
 - RimSort version: [Edge 57d060a](https://github.com/RimSort/RimSort/releases/tag/Edge) 
 - Please provide a `RimSort.log`: *empty file*
 - Compiled Rimsort

**Additional context**
After a quick googling this happens due to the missing library `libxcb-cursor.so.0`, installing the package `xcb-util-cursor` (on arch linux) seems to fix this issue.

Maybe add the missing library to the compiled Rimsort.

**Comment by Chunnyluny** [comment]
@potatoo14 Will be fixed in another overall effort for Linux compatibility. Closing as duplicate of #35
