### ISSUE TITLE
FIXME: Cataclysm Bug

### ISSUE THREAD

**Issue by KoboDev** [RimSort/RimSort#246]
**Describe the bug**
This bug when done, can open alot copies of itself, telling the person that the software in question crashed.
Except, I got 447 brand new windows crashing my system telling me, it crashed, in the most brutal way.

**To Reproduce**
1. Edit your modlist if you wish, it does not matter.
2. Open Up programs you use normally, Steam, Discord, Maybe a background streaming service.
3. Run Rimworld at least once, so it stores in ram cache.
4. Go back to rimsort, Press Restore Active State.
5. Profit, if enough ram is already used, which is actually a thing with a big modlist.
Note: Graphical vomit will occur if you switch windows and back to rimsort after freezing stops, will also freeze for a min if you also switch windows.

**Expected behavior**
Restore Active State, Which normally should do nothing if you havent edited your list, and also when you do save your list.

**Screenshots**
![image](https://github.com/RimSort/RimSort/assets/78581464/9727c7d2-5724-4ee8-bcb9-f97d5781233a)
![image](https://github.com/RimSort/RimSort/assets/78581464/2167641b-de54-4634-90fb-4f87afd92e79)

**Please complete the following information:**
 - OS: Arch Linux x86_64 
 - RimSort version: EDGE 57d060a
 - Please provide a `RimSort.log`: [RimSort.log](https://github.com/RimSort/RimSort/files/13814394/RimSort.log)
 - Are you running from Python interpreter or from a compiled RimSort release? Github Release

**Additional context**

This may crash your computer, or freeze it for a while.
Can be Avoided with no Ram Usage, which with rimworld is hard.

**Comment by twstagg** [comment]
Fixed
