### ISSUE TITLE
FIXME:  Crash on opening the browser

### ISSUE THREAD

**Issue by Lippiece** [RimSort/RimSort#249]
**Describe the bug**
When I click "Browse Workshop", app crashes.

**To Reproduce**
1. Open the app.
2. Click "Browse Workshop"

**Expected behavior**
The browser should open.

**Please complete the following information:**
 - OS: Garuda Linux
 - RimSort version: alpha_v1.0.6.2_hf
 - Please provide a `RimSort.log`:
 - Are you running from Python interpreter or from a compiled RimSort release?
    From aur package (effectively downloaded from Releases).

<details><summary>**Additional context**</summary>

```
qt.webenginecontext: 

GL Type: disabled
Surface Type: DefaultRenderableType
Surface Profile: NoProfile
Surface Version: 2.0
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: no

Init Parameters:
  *  application-name RimSort 
  *  browser-subprocess-path /opt/rimsort/QtWebEngineProcess 
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-gpu  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  no-sandbox  
  *  use-gl disabled 

QRhiGles2: Failed to create temporary context
QRhiGles2: Failed to create context
Failed to create QRhi for QBackingStoreRhiSupport
QPixmap::scaled: Pixmap is a null pixmap
QRhiGles2: Failed to create temporary context
QRhiGles2: Failed to create context
Failed to create QRhi for QBackingStoreRhiSupport
QQuickWidget: Failed to get a QRhi from the top-level widget's window
QQuickWidget::resizeEvent() no QRhi
QRhiGles2: Failed to create temporary context
QRhiGles2: Failed to create context
Failed to create QRhi for QBackingStoreRhiSupport
QQuickWidget: Failed to get a QRhi from the top-level widget's window
QQuickWidget: Attempted to render scene with no rhi
No suitable graphics backend found

QPixmap::scaled: Pixmap is a null pixmap
/usr/bin/rimsort: line 3: 209662 Segmentation fault      (core dumped) ./RimSort.bin $@
```

</details>

**Comment by Lippiece** [comment]
I see that the edge release doesn't have this problem. However, it has another one: when I press "Sort", a few mods end up disabled.

**Comment by Limfjorden** [comment]
Which ones? Local ones?

**Comment by Lippiece** [comment]
> Which ones? Local ones?

![image](https://github.com/RimSort/RimSort/assets/47634624/9a2b2358-0d79-453a-a14e-31edf739c048)

**Comment by Limfjorden** [comment]
@Lippiece Do you also have steam versions of those mods, or only local?

**Comment by Limfjorden** [comment]
> I see that the edge release doesn't have this problem. However, it has another one: when I press "Sort", a few mods end up disabled.

If this issue is fixed on Edge, then it should be closed.

**Comment by Lippiece** [comment]
> > I see that the edge release doesn't have this problem. However, it has another one: when I press "Sort", a few mods end up disabled.
> 
> If this issue is fixed on Edge, then it should be closed.

I agree. I also think I should open a new one for the other problem.
