### ISSUE TITLE
FIXME: SteamCMD wants to clear entire steam-mod directory

### ISSUE THREAD

**Issue by Limfjorden** [RimSort/RimSort#252]
**Describe the bug**
When trying to reinstalll SteamCMD, it asks to clear the entire steammod directory.

**To Reproduce**
1. Setup steamCMD
2. Accept reinstall of steamCMD
3. See request in the log

**Expected behavior**
SteamCMD reinstalls without wanting to clear the directory.

**Screenshots**

**Please complete the following information:**
 - OS: MacOS 13.6.3
 - RimSort version: Alpha v1.0.6.2-hf [Edge 57d060a]
 - Please provide a `RimSort.log`: [rimsort_log.txt](https://github.com/RimSort/RimSort/files/13998572/rimsort_log.txt)
 - Are you running from Python interpreter or from a compiled RimSort release? 

I am running from a compiled release.

**Additional context**
SteamCMD log: [steamcmd_log.txt](https://github.com/RimSort/RimSort/files/13998571/steamcmd_log.txt)

**Comment by twstagg** [comment]
The messages states that you need to remove the existing file if you would like to symlink it to that destination. You will need to remove the source path that is there for RimSort to be able to complete that symlink process
