### ISSUE TITLE
FIXME: "Run game" button does not launch the game

### ISSUE THREAD

**Issue by Limfjorden** [RimSort/RimSort#253]
**Describe the bug**
The game does not launch when clicking "run game". However, some text appears in the bottom left corner when I click the button. It says "Starting Rimworld", but this does not happen.

**To Reproduce**
1. Launch
2. Click on "run game"
3. See error: Game does not launch

**Expected behavior**
The button should launch the game.

**Please complete the following information:**
 - OS: MacOS 13.6.3
 - RimSort version: Alpha v1.0.6.2-hf [Edge 57d060a]
 - Please provide a `RimSort.log`: 
[Rimsort_log.txt](https://github.com/RimSort/RimSort/files/14035896/Rimsort_log.txt)
 - I am running from a compiled release

**Additional context**
I think this issue is present on all platforms, not just MacOS.

Archer (harmchair) on Discord confirms the Issue is present on Windows 10 as well.

**Comment by Chunnyluny** [comment]
This is a known issue, I have Windows 11, and it won't run as well. It is planned to be worked on. It might have been caused since the whole settings panel has been changed, and accidentally a line is missing for the app to run the game. I hope Twsta or Captain arbitrary or Lion could fix this function to work again!! Maybe you and me can compare versions, I have noticed that the version of August had the run button working, so we can take a look to see which line is missing. If you can find anything, please let us know here or in the discord server!

**Comment by oceancabbage** [comment]
Looking into this now. Very strange because if I run RimSort locally through Python the `Run Game` button works. i.e. clone RimSort, run `python3 distribute.py`, then `python3 -m app`, then click `Run Game` -> RimWorld opens. Maybe it has to do with SteamWorks being wonky after getting packaged up. Will do some more testing

**Comment by Chunnyluny** [comment]
I also thought that Lion has looked into this issue, not sure if he found out about it.

**Comment by nonnonstop** [comment]
When I clicked on the “Run” button, the following error message appeared in the console.

```
Traceback (most recent call last):
  File "D:\Projects\RimSort\build\__main__.dist\__main__.py", line 19, in <module __parents_main__>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\Projects\RimSort\build\__main__.dist\app\controllers\app_controller.py", line 7, in <module app.controllers.app_controller>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\Projects\RimSort\build\__main__.dist\app\controllers\main_window_controller.py", line 8, in <module app.controllers.main_window_controller>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\Projects\RimSort\build\__main__.dist\app\views\main_window.py", line 27, in <module app.views.main_window>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\Projects\RimSort\build\__main__.dist\app\views\main_content_panel.py", line 70, in <module app.views.main_content_panel>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\Projects\RimSort\build\__main__.dist\app\views\mods_panel.py", line 399, in <module app.views.mods_panel>
  File "D:\Projects\RimSort\build\__main__.dist\app\views\mods_panel.py", line 400, in ModListIcons
  File "D:\Projects\RimSort\build\__main__.dist\app\utils\app_info.py", line 45, in __init__
ValueError: AppInfo must be initialized once with __file__.
```

Note that Nuitka's `--disable-console` option is commented out to display this message.
https://github.com/RimSort/RimSort/blob/4e8df2f2a859b59f46f3a076caad4b6df4b9ed57/distribute.py#L100

After the following modification, It works successfully.

https://github.com/RimSort/RimSort/blob/4e8df2f2a859b59f46f3a076caad4b6df4b9ed57/app/__main__.py#L14-L17

```diff
diff --git a/app/__main__.py b/app/__main__.py
index cc8b561..d68f8e9 100644
--- a/app/__main__.py
+++ b/app/__main__.py
@@ -11,10 +11,9 @@ from loguru import logger

 from app.utils.app_info import AppInfo

-if __name__ == "__main__":
-    # One-time initialization of AppInfo class (this must be done in __main__ so we can use __file__)
-    # Initialize as early as possible!
-    AppInfo(main_file=__file__)
+# One-time initialization of AppInfo class (this must be done in __main__ so we can use __file__)
+# Initialize as early as possible!
+AppInfo(main_file=__file__)

 from app.controllers.app_controller import AppController

```

**Comment by LionelColaso** [comment]
> When I clicked on the “Run” button, the following error message appeared in the console.
> 
> ```
> Traceback (most recent call last):
>   File "D:\Projects\RimSort\build\__main__.dist\__main__.py", line 19, in <module __parents_main__>
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "D:\Projects\RimSort\build\__main__.dist\app\controllers\app_controller.py", line 7, in <module app.controllers.app_controller>
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "D:\Projects\RimSort\build\__main__.dist\app\controllers\main_window_controller.py", line 8, in <module app.controllers.main_window_controller>
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "D:\Projects\RimSort\build\__main__.dist\app\views\main_window.py", line 27, in <module app.views.main_window>
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "D:\Projects\RimSort\build\__main__.dist\app\views\main_content_panel.py", line 70, in <module app.views.main_content_panel>
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "D:\Projects\RimSort\build\__main__.dist\app\views\mods_panel.py", line 399, in <module app.views.mods_panel>
>   File "D:\Projects\RimSort\build\__main__.dist\app\views\mods_panel.py", line 400, in ModListIcons
>   File "D:\Projects\RimSort\build\__main__.dist\app\utils\app_info.py", line 45, in __init__
> ValueError: AppInfo must be initialized once with __file__.
> ```
> 
> Note that Nuitka's `--disable-console` option is commented out to display this message.
> 
> https://github.com/RimSort/RimSort/blob/4e8df2f2a859b59f46f3a076caad4b6df4b9ed57/distribute.py#L100
> 
> After the following modification, It works successfully.
> 
> https://github.com/RimSort/RimSort/blob/4e8df2f2a859b59f46f3a076caad4b6df4b9ed57/app/__main__.py#L14-L17
> 
> ```diff
> diff --git a/app/__main__.py b/app/__main__.py
> index cc8b561..d68f8e9 100644
> --- a/app/__main__.py
> +++ b/app/__main__.py
> @@ -11,10 +11,9 @@ from loguru import logger
> 
>  from app.utils.app_info import AppInfo
> 
> -if __name__ == "__main__":
> -    # One-time initialization of AppInfo class (this must be done in __main__ so we can use __file__)
> -    # Initialize as early as possible!
> -    AppInfo(main_file=__file__)
> +# One-time initialization of AppInfo class (this must be done in __main__ so we can use __file__)
> +# Initialize as early as possible!
> +AppInfo(main_file=__file__)
> 
>  from app.controllers.app_controller import AppController
> ```

i just tried and it works, in case you want to push the fix yourself we will hold on to the current pull request and honor your request
https://github.com/RimSort/RimSort/pull/315

**Comment by nonnonstop** [comment]
@LionelColaso 
use the pull request you created.
thank you.

**Comment by LionelColaso** [comment]
> @LionelColaso use the pull request you created. thank you.

Between Thank-you for the Fix and help with Suggestion somehow it never crossed our mind and it was long over due 
if you had not helped it would taken a lot of time and effort for us to get it
