### ISSUE TITLE
FIXME: Unable to click "close" in "succesful export to rentry" popup

### ISSUE THREAD

**Issue by Limfjorden** [RimSort/RimSort#254]
**Describe the bug**
When exporting to rentry, I get a popup giving me the link. However, since all the mods in the mod list are listed, the popup goes of the screen and I can't click the "close" button.

**To Reproduce**
1. Save a modlist
2. Click on "File"
3. Hover on "Export"
4. Select "Export" to rentry
5. Wait for it to export.
6. See large window

**Expected behavior**
There should be a close button visible.

**Screenshots**

**Please complete the following information:**
 - OS: MacOS 13.6.3
 - RimSort version: Alpha v1.0.6.2-hf [Edge 57d060a]
 - Please provide a `RimSort.log`: 
[Rimsort_log.txt](https://github.com/RimSort/RimSort/files/14036534/Rimsort_log.txt)
 - I am running a compliled release.

**Additional context**
It is possible to work around the problem by pressing enter while on the popup, but it should none the less be fixed.

I suggest only providing the link and not also the mod list. That way the window won't be so impracticaly large.

**Comment by twstagg** [comment]
While this is not intended behavior, it is also not really a bug. However, this dialog can be rebuilt by anybody who chooses to improve it.

**Comment by LionelColaso** [comment]
can you conform that it still happens and if it does can u post a screenshot cause this is what i get on Windows
![image](https://github.com/RimSort/RimSort/assets/2488703/59a541a5-0824-4643-95de-543e16c077b3)

**Comment by twstagg** [comment]
This should now be fixed.
