### ISSUE TITLE
Implement grepping

### ISSUE THREAD

**Issue by Limfjorden** [RimSort/RimSort#256]
**Is your feature request related to a problem? Please describe.**
In Rimpy, it is possible to search all mods for strings. This is immensely useful when troubleshooting and fixing errors in mods. This is not present in Rimsort.

**Describe the solution you'd like**
I'd like for there to be a UI for grepping (searching) the steam mods, local mods, as well as the game files and config files if possible.

**Describe alternatives you've considered**
It's currently possible to do this through the terminal on mac/linux, but a UI would be more user friendly.

**Comment by twstagg** [comment]
This task is already planned & being factored in #27
