### ISSUE TITLE
FIXME: Optimize textures not working

### ISSUE THREAD

**Issue by miwitham** [RimSort/RimSort#258]
**Describe the bug**
When clicking the **Optimize textures** button in RimSort I am immediately given the following error:

```
ヽ༼ ຈل͜ຈ༼ ▀̿̿Ĺ̯̿̿▀̿ ̿༽Ɵ͆ل͜Ɵ͆ ༽ﾉ
ERROR: todds was not found. If you are running from source, please ensure you have followed the correct steps in the Development Guide:
https://github.com/RimSort/RimSort/wiki/Development-Guide

Please reach out to us for support at: https://github.com/oceancabbage/RimSort/issues
```

I am using the _Default quality_ preset and the only checkbox checked is _Force todds to only target mods in the active list_.

**To Reproduce**
1. Click the **Optimize textures** button.
2. Immediately observe that a RimSort - todds texture encoder window has launched stating the above error.

**Expected behavior**
Expect that some form of texture optimization process is verbosely logged for as it is occurring in the window that opened.

**Screenshots**
<img width="912" alt="image" src="https://github.com/RimSort/RimSort/assets/52472104/ff9b6321-47dc-47d5-8e37-3899344ee0eb">

**Please complete the following information:**
 - OS: MacOS Sonoma 14.2.1
 - RimSort version: Alpha-v1.0.6.2-hf
 - Please provide a `RimSort.log`: [RimSort.log](https://github.com/RimSort/RimSort/files/14216735/RimSort.log)
 - Are you running from Python interpreter or from a compiled RimSort release? Compiled release.

**Additional context**
I verified that the download was for Darwin_arm.

**Comment by twstagg** [comment]
Please use the latest Edge release. The build you appear to be using hear is outdated. There will be a new Alpha release after more progress is made.

This issue was specific to that build, in which i believe we neglected to bundle todds for MacOS ARM
