### ISSUE TITLE
FIXME: Wrong order for [NL] Facial Animation - WIP and [NL] Facial Animation - Experimentals

### ISSUE THREAD

**Issue by lisanhu** [RimSort/RimSort#259]
**Describe the bug**
The sorting for active mods do not respect the dependence or loadAfter relations between these two mods

**To Reproduce**
1. Click on "Sort"

**Expected behavior**
 [NL] Facial Animation - Experimentals  is listed after [NL] Facial Animation - WIP

**Screenshots**
After sorting:
![image](https://github.com/RimSort/RimSort/assets/3086096/4cdcab78-481c-4045-904d-93968707dc5a)

**Please complete the following information:**
 - OS: Pop OS 22.04
 - RimSort version: 1.0.6.2-hf
 - Please provide a `RimSort.log`: http://0x0.st/Hdut.log
 - Are you running from Python interpreter or from a compiled RimSort release? compiled RimSort release

**Additional context**
Also, I noticed that after RimSort modified ModsConfig.xml, RimPy is no longer able to recognize it correctly.

**Comment by lisanhu** [comment]
Hi! I just want to add one more case for this issue

![image](https://github.com/RimSort/RimSort/assets/3086096/e35c4902-11ce-45c4-90ba-dfbb11314c34)

In the mod "More Scenario Searchbars", the dependency to "Scenario Searchbars" in the About/About.xml file 

```
<?xml version="1.0" encoding="utf-8"?>
<ModMetaData>
	<packageId>RunningBugs.MoreScenarioSearchbars</packageId>
	<name>More Scenario Searchbars</name>
	<author>RunningBugs</author>
	<supportedVersions>
		<li>1.4</li>
	</supportedVersions>

	<modDependencies>
		<li>
			<packageId>nimrag.scenariosearchbar</packageId>
			<displayName>Scenario Searchbars</displayName>
			<steamWorkshopUrl>https://steamcommunity.com/sharedfiles/filedetails/?id=3052467818</steamWorkshopUrl>
		</li>
	</modDependencies>

	<incompatibleWith>
		<!-- <li>username.modname</li> -->
	</incompatibleWith>

	<loadAfter>
		<!-- <li>username.modname</li> -->
	</loadAfter>

	<description>More Scenario Searchbars on Create Incident, credits to https://steamcommunity.com/sharedfiles/filedetails/?id=3052467818 for his work on creating the base function, which I use in this patch.

I'm just reuse the code in Scenario Searchbars and create one more patch for CreateIncident.
	</description>
</ModMetaData>

```

However, after clicking on sorting it's not in the correct order. I've turned off both the steam database and community database.

**Comment by twstagg** [comment]
@oceancabbage would you mind taking a look at this one with the other things we talked about re: sorting?

**Comment by hk21702** [comment]
@lisanhu Sorry for not getting on this earlier. Can you do me a favor and attempt this on the latest version, once using alphabetical mode and once using topological mode. Let me know if there is a difference in terms of proper sorting between the two methods.

**Comment by lisanhu** [comment]
@hk21702 Hi! Sorry I just saw your mention. I just pulled the current main branch and the issue seems to be solved. Thank you so much for looking into this!
