### ISSUE TITLE
FIXME: ERROR: todds was not found. 

### ISSUE THREAD

**Issue by bermagambet** [RimSort/RimSort#266]
**Describe the bug**
macOS M2, alpha-v1.0.6.2-hf - "ERROR: todds was not found" error while trying to optimize textures.

**To Reproduce**
1. Open RimSort
2. Click on "Optimize textures"
3. See error

**Expected behavior**
Optimization of textures window/promt after clicking "Optimize textures". 

**Screenshots**
<img width="787" alt="image" src="https://github.com/RimSort/RimSort/assets/36257463/4759cb9f-39ca-4f87-abf0-ef209574bcc2">

**Please complete the following information:**
 - OS: macOS 14.0 (23A344)
 - RimSort version: alpha-v1.0.6.2-hf
 - Please provide a `RimSort.log`: 
[rimsort.logs.txt](https://github.com/RimSort/RimSort/files/14392021/rimsort.logs.txt)
 - Are you running from Python interpreter or from a compiled RimSort release? Compiled release

**Additional context**
Rimworld steam version, first run of Rimsort.

**Comment by twstagg** [comment]
Please use Edge release. This issue should be fixed there, as we now bundle todds for MacOS arm64
