### ISSUE TITLE
Suggestion: Don't show update dialog when version is up to date

### ISSUE THREAD

**Issue by DarkShadow44** [RimSort/RimSort#269]
**Is your feature request related to a problem? Please describe.**
The update dialog at the start is annoying. I don't think it's useful to show that there are no updates.

**Describe the solution you'd like**
Only show a dialog message when there is a new version. Don't show anything if there's nothing new.

**Describe alternatives you've considered**
An option to disable the automatic update check in the GUI would be useful as well.

**Comment by twstagg** [comment]
> **Is your feature request related to a problem? Please describe.** The update dialog at the start is annoying. I don't think it's useful to show that there are no updates.
> 
> **Describe the solution you'd like** Only show a dialog message when there is a new version. Don't show anything if there's nothing new.
> 
> **Describe alternatives you've considered** An option to disable the automatic update check in the GUI would be useful as well.

I don't think this is present in the current track on Edge. There is a much better system than previously used, that can be fully disabled from automatically happening via Settings now. If you are on Alpha I suggest you use Edge now instead.

**Comment by DarkShadow44** [comment]
Works nicely, thanks!
