### ISSUE TITLE
FIXME: Sort active mods is slow

### ISSUE THREAD

**Issue by DarkShadow44** [RimSort/RimSort#270]
**Describe the bug**
When clicking "Sort active mods" it takes a few seconds until it's done. in RimPy it's pretty much instant, and I kinda miss that.

**To Reproduce**
Clock on "Sort active mods" 

**Expected behavior**
Should work faster

**Please complete the following information:**
 - OS: Arch Linux
 - Please provide a `RimSort.log`: [RimSort.log](https://github.com/RimSort/RimSort/files/14451987/RimSort.log)

 - Compiled release Alpha-v1.0.6.2-hf

**Comment by twstagg** [comment]
Closing this as there have been huge improvements in general recently. Please try latest Edge build and let me know via another issue your specific feedback. Thank you for taking the time.

**Comment by DarkShadow44** [comment]
Works nicely, thanks!
