### ISSUE TITLE
FIXME: Steamdb build crash (updated log)

### ISSUE THREAD

**Issue by Brissinger** [RimSort/RimSort#278]
**Describe the bug**
After clicking Build database (steam) and setting up file name it crashes to desktop after 2-3 seconds with no massage.

**Please complete the following information:**
 - OS: WIN 11
 - Ryzen 5 3600, RTX 3060, 24GB Ram
 - RimSort version: latest edge
 - Log: [RimSort.log](https://github.com/RimSort/RimSort/files/14732956/RimSort.log) {updated}
 - Screenshot: <details>
![Zrzut ekranu 2024-03-23 174241](https://github.com/RimSort/RimSort/assets/72404411/bbca9ffb-7018-40dd-9181-fc5f33fe232d)</details>
 - Python 3.12.2 from official website

**Comment by twstagg** [comment]
Thanks for opening this and for your report. DB Builder needs overhauled, and probably separated into it's own program at this point. I will be rewriting it.

This log was very helpful. There is definitely a bug there that needs to be fixed.

**Comment by Chunnyluny** [comment]
I also have a crash on Steam Database build, here is my RimSort log.old: https://0x0.st/X-Ok.old.log

I hope you can find out why my database crashed.

**Comment by M0rr1s0n** [comment]
I have the same issue, crashing with the same last msg in the log. 
[RimSort.log](https://github.com/RimSort/RimSort/files/15051228/RimSort.log)

**Comment by twstagg** [comment]
@Brissinger @M0rr1s0n if you guys could also make sure to turn on debug in settings -> advanced before producing logs, we could glean additional info

**Comment by M0rr1s0n** [comment]
Still crashing for me on the newest Edge 699c45e, I reset the %appdata% folder before using the newest version and turned on debug logs:
[RimSort.log](https://github.com/RimSort/RimSort/files/15118887/RimSort.log)

**Comment by Brissinger** [comment]
Still crashing, downgraded Python to 3.11.9. Turned on debug
[RimSort.log](https://github.com/RimSort/RimSort/files/15133359/RimSort.log)

**Comment by Brissinger** [comment]
Tried to Build Steam database. Cashed but error looks different and window doesn't hang on. Log file is about half size smaller also. Latest log:
[RimSort.log](https://github.com/RimSort/RimSort/files/15247288/RimSort.log)
