### ISSUE TITLE
FIXME: 

### ISSUE THREAD

**Issue by Brissinger** [RimSort/RimSort#279]
**Describe the bug**
When I launch Rimsort it detects core and dlcs as mods with missing data

**Please complete the following information:**
 - OS: WIN 11
 - RimSort version: Latest stable/latest edge
 - Log: [RimSort.log](https://github.com/RimSort/RimSort/files/14731050/RimSort.log)
 - Screenshot: https://github.com/RimSort/RimSort/assets/72404411/240c36d6-8ed2-4c4c-b821-0f737ff4bfb4
 - Python 3.11 from official website

**Comment by LionelColaso** [comment]
Looking at the screenshot you are using too old version of rimsort please try the latest eedge version of rimsort
