### ISSUE TITLE
FIXME: RimSort DB Builder hangs at 0%

### ISSUE THREAD

**Issue by ezadEzanee** [RimSort/RimSort#280]
**Describe the bug**
RImSort hangs at 0%

![CleanShot - RimSort - RimSort - DB Builder (no_local) - 2024-04-02 at 10 13 36](https://github.com/RimSort/RimSort/assets/18095325/d94c46f6-85ce-4e32-b5a6-c160d979f9d3)

![CleanShot - Console - RimSort log - 2024-04-02 at 10 14 39](https://github.com/RimSort/RimSort/assets/18095325/53f03cfc-af2e-4c67-a824-3d1578dcfb1d)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - OS: [e.g. iOS] macOS Sonoma 14.4
 - RimSort version: RimSort Alpha-v1.0.6.2-hf
 - Please provide a `RimSort.log`:http://0x0.st/XzyY.log
 - Are you running from Python interpreter or from a compiled RimSort release? Compiled

**Additional context**

**Comment by twstagg** [comment]
Thanks for opening this and for your report. DB Builder needs overhauled, and probably separated into it's own program at this point. I will be rewriting it.

**Comment by twstagg** [comment]
This has been fixed.
