### ISSUE TITLE
FIXME: Trouble importing python request package. Likely user issue.

### ISSUE THREAD

**Issue by xynerorias** [RimSort/RimSort#288]
**Describe the bug**

_Can't seem to build from source. After cloning, with Python and PySide installed, trying to run the .\distribute.py file errors out on importing the 'requests' package. Tried to uninstall and reinstall the package with pip to no avail. It's correctly installed (c.f screenshot)._

_The screenshot shows trying to build inside VSCode but it happens as well when using PowerShell._

**To Reproduce**
1. Clone the repo with html with `git clone https://github.com/RimSort/RimSort.git`
2. `cd .\Rimsort`
3. `python .\distribute.py`
4. Error when trying to run the script :

```
Traceback (most recent call last):
  File "D:\Modding\RimSort\RimSort\distribute.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Expected behavior**

_Auto-building correctly, no error when importing the 'requests' package._

**Screenshots**

![image](https://github.com/RimSort/RimSort/assets/43299926/1a9762df-66b7-41c5-98cd-3fc187dfdfd0)

**Please complete the following information:**
 - OS: _Windows 11 23H2_
 - RimSort version: _Latest pull from main branch._
 - Are you running from Python interpreter or from a compiled RimSort release? _Yes. Well, trying to._

**Additional context**

_Tried reinstalling as shown in the screenshot, have the latest Python windows version and PySide as well. Tried running with `python` and `python3`, and un/reinstalling with `pip` and `pip3`. Didn't change anything unsurprisingly, but you never know sometimes._

**Comment by xynerorias** [comment]
As suspected, dumb user issue, sorry for clogging up. Pip wasn't added to PATH.

Works as expected after the following :

```
PS D:\Modding\RimSort\RimSort> python -m pip install virtualenv
C:\msys64\ucrt64\bin\python.exe: No module named pip
PS D:\Modding\RimSort\RimSort> python -m ensurepip
Looking in links: c:\Users\Axus\AppData\Local\Temp\tmp41668sy2
Processing c:\users\axus\appdata\local\temp\tmp41668sy2\setuptools-65.5.0-py3-none-any.whl
Processing c:\users\axus\appdata\local\temp\tmp41668sy2\pip-23.0.1-py3-none-any.whl
Installing collected packages: setuptools, pip
Successfully installed pip-23.0.1 setuptools-65.5.0
PS D:\Modding\RimSort\RimSort> python -m pip install requests
Collecting requests
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 556.7 kB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.7-py3-none-any.whl (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 kB 3.5 MB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.2.1-py3-none-any.whl (121 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.1/121.1 kB 6.9 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 5.0 MB/s eta 0:00:00
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.3.2-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 2.4 MB/s eta 0:00:00
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2024.2.2 charset-normalizer-3.3.2 idna-3.7 requests-2.31.0 urllib3-2.2.1

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
PS D:\Modding\RimSort\RimSort> python .\distribute.py
```

**Comment by LionelColaso** [comment]
you can just follow the link and scroll to end of page and followed the comands
https://github.com/RimSort/RimSort/wiki/Development-Guide

**Comment by xynerorias** [comment]
Just in case other people have trouble building, and since PySide and their versioning is a dumpster fire and you're shit out of luck if you're on python 3.12, here are some steps to help you out :

`winget install python.python.3.11`
`py -3.11 -m ensurepip` --> may or may not need it, just to double check
`py -3.11 -m pip install pyside6`
`py -3.11 -m pip install requests` --> if you get the requests import error
`py -3.11 .\distribute.py`

Should build correctly after that.

**Comment by LionelColaso** [comment]
> Just in case other people have trouble building, and since PySide and their versioning is a dumpster fire and you're shit out of luck if you're on python 3.12, here are some steps to help you out :
> 
> `winget install python.python.3.11` `py -3.11 -m ensurepip` --> may or may not need it, just to double check `py -3.11 -m pip install pyside6` `py -3.11 -m pip install requests` --> if you get the requests import error `py -3.11 .\distribute.py`
> 
> Should build correctly after that.

it already mentions
![image](https://github.com/RimSort/RimSort/assets/2488703/b95a5699-2dcf-4b36-85f7-fdbdae11221c)

**Comment by xynerorias** [comment]
My ability to read remains subpar apparently. Cheers.
