### ISSUE TITLE
FIXME: A random crash after days of using on Linux

### ISSUE THREAD

**Issue by lisanhu** [RimSort/RimSort#292]
**Describe the bug**
Today when I was in normal use and just clicked on the refresh button, the program crashed.

**To Reproduce**
Normal use until we are lucky enough to trigger it.

**Expected behavior**
It should not crash anyway.

**Screenshots**
I'll put the logs here: https://0x0.st/XoH1.old.log

**Please complete the following information:**
 - OS: Pop OS 22.04 (Ubuntu based)
 - RimSort version: main branch f50e6c1474049203011bdb2c11ed71d75f206327
 - Please provide a `RimSort.log`: https://0x0.st/XoH1.old.log
 - Are you running from Python interpreter or from a compiled RimSort release? From running `./distribute.py` and then run the binary in the build folder.

**Additional context**

**Comment by lisanhu** [comment]
I want to confirm this problem still exists in the current edge version 794a20f

![Screenshot from 2024-04-21 01-17-31](https://github.com/RimSort/RimSort/assets/3086096/33a5ed1f-c50b-43cd-ac6c-fd2cc6c0b8d3)

**Comment by twstagg** [comment]
@lisanhu Please test new build and let me know if issue is still present, we will need to debug if it is.

**Comment by lisanhu** [comment]
Thanks for the update! I'll be testing on that.

**Comment by twstagg** [comment]
Please reopen if this behavior continues / you have more descriptive info on how to reproduce
