### ISSUE TITLE
FIXME: A minor UI problem looks like because of the lazy loading

### ISSUE THREAD

**Issue by lisanhu** [RimSort/RimSort#293]
**Describe the bug**
When starting RimSort from command line in Linux. The window is not scale to the full screen. Then I maximize the window. The list of mods are not show in full unless I scroll the scrollbar.

**To Reproduce**
1. Open the program not in maximized state
2. Maximize it

**Expected behavior**
There should be no missing mods in the long lists

**Screenshots**
1. small window at the beginning
![image](https://github.com/RimSort/RimSort/assets/3086096/12ee30d7-1a33-4ea8-b71c-7f6948bfb848)

2. maximized window
![image](https://github.com/RimSort/RimSort/assets/3086096/213f7838-28c6-4bd2-b937-4ab685fb33bc)

3. A little bit of scrolling
![image](https://github.com/RimSort/RimSort/assets/3086096/36139a16-de83-404e-8ce7-d12739b07fd5)

**Please complete the following information:**
 - OS: Pop OS 22.04 [Ubuntu based]
 - RimSort version: main branch f50e6c1474049203011bdb2c11ed71d75f206327
 - Please provide a `RimSort.log`: https://0x0.st/XoHO.log
 - Are you running from Python interpreter or from a compiled RimSort release? Compiled using `./distribute.py`

**Additional context**

**Comment by twstagg** [comment]
Good catch! Fixing this now.
