### ISSUE TITLE
Suggestion: Allow setting RimWorld run arguments

### ISSUE THREAD

**Issue by lisanhu** [RimSort/RimSort#298]
**Is your feature request related to a problem? Please describe.**
In previous version ( when the buttons were in the right side ), we were able to set up the run arguments for rimworld by clicking the 3 dots part of the button "Run game". I could not find this functionality in the current release (794a20f).

**Describe the solution you'd like**
I would like the feature coming back or in a different place?

**Describe alternatives you've considered**

**Additional context**

**Comment by LionelColaso** [comment]
You can find this in advanced settings at the bottom

**Comment by lisanhu** [comment]
Cool!
