### ISSUE TITLE
FIXME: Must wait several seconds between closing RimSort and trying to open it again

### ISSUE THREAD

**Issue by divineDerivative** [RimSort/RimSort#301]
**Describe the bug**
After closing RimSort, if I immediately try to open it again the little blue circle will appear for a bit but the program never opens. RimSort disappears from the task manager as soon as it is closed.

**To Reproduce**
Close RimSort and then try to open it again within about 5 seconds.

**Expected behavior**
That the program either open again immediately, or for there to be some indication in the task manager that it has not finished closing, if that's what's preventing it from opening again.

**Please complete the following information:**
OS: Windows 10
RimSort version: Alpha-v1.0.6.2-hf [Edge 794a20f]
Please provide a RimSort.log: https://0x0.st/Xo6n.log
Are you running from Python interpreter or from a compiled RimSort release? Compiled Edge release

**Comment by twstagg** [comment]
Hi @divineDerivative ,

Do you see any output in the console that pops up when you experience this issue?
