### ISSUE TITLE
FIXME: Mod updating feature on Win11 Edge 6db22ad 

### ISSUE THREAD

**Issue by Quarta-feira** [RimSort/RimSort#304]
**Describe the bug**
I cannot update mods through RimSort, it keeps processing indefinitely. Tried this time with only the '[FSF] Better Anomaly Loot' mod (size 227.675 KB) 
I can see on windows task manager RimSort taking up processing time, but it never ends.

**To Reproduce**
1. Open RimSort
2. On the 'updates found for workshop mods' window, select any mod
3. Click 'Update mods'

**Expected behavior**
The mod updating in a timely manner, and the app not taking every bit of processing power available.

**Screenshots**
![image](https://github.com/RimSort/RimSort/assets/87493008/3fd057ca-5687-4b5c-b1a5-21a1119634d8)

![image](https://github.com/RimSort/RimSort/assets/87493008/f1e0d292-77c9-47c1-a821-8c4a458862ca)

**Please complete the following information:**
 - OS: Win11
 - RimSort version:  Edge 6db22ad 
 - Please provide a `RimSort.log`: I can't generate a log because the file button is unclickable when running the update process
 - Are you running from Python interpreter or from a compiled RimSort release? Compiled

**Additional context**

**Comment by twstagg** [comment]
Hi. You can find the log files at `%AppData%\RimSort\Logs`

Please make sure you have debug logging enabled (Settings -> advanced) and upload. 

I am aware if issues with Steamworks on Windows as well. I setup w11 last night and am looking into things myself as well.

**Comment by Quarta-feira** [comment]
Sure, here is the log, just tried updating 'blood animations' mod.

[RimSort.log](https://github.com/RimSort/RimSort/files/15111159/RimSort.log)

I saw you were looking into it on discord, that's why I decided to report here, to give you more context to look into.
Tnx :)

**Comment by twstagg** [comment]
@Quarta-feira This should be resolved. Please let me know if it is not, and we can reopen.
