### ISSUE TITLE
FIXME: RimSort failed to load local mods' data

### ISSUE THREAD

**Issue by lisanhu** [RimSort/RimSort#305]
**Describe the bug**
RimSort reported missing mods error for local mods. And those were in the correct folder.

**To Reproduce**
1. Have a modlist that contains some of the local mods.
2. Launch RimSort and it will report several local mods missing (not all local mods are missing, still mysterious what mods will be missing)

**Expected behavior**
Should be able to load local mods

**Screenshots**
![image](https://github.com/RimSort/RimSort/assets/3086096/249d4cdb-98ff-4708-a2d6-8fd039075e50)

**Please complete the following information:**
 - OS: [e.g. iOS]  Pop OS 22.04 (Ubuntu-based)
 - RimSort version: 6db22ad
 - Please provide a `RimSort.log`: https://0x0.st/XHmb.log
 - Are you running from Python interpreter or from a compiled RimSort release?
compiled

**Additional context**

**Comment by lisanhu** [comment]
Ah! I might have found the step to reproduce it!

1. Have a local mod
2. Put a file named `PublishedFileId.txt` in its About/ folder
3. Refresh RimSort

**Comment by divineDerivative** [comment]
I had this happen in both RimSort and RimPy with the same local mod. Only difference is that RimPy did have the mod in the inactive list while RimSort did not. I can confirm that none of my local mods that have a PublishedFieldId.txt can be found by RimSort, and it does find all of them without the PublishedFieldId.txt.
