### ISSUE TITLE
FIXME: RimSort removing data from ModsConfig

### ISSUE THREAD

**Issue by divineDerivative** [RimSort/RimSort#306]
**Describe the bug**
When RimSort saves a mod list, it is removing both the `version` and `knownExpansions` node from ModsConfig.xml. This causes RimWorld to add all owned expansions to the end of the mod list on launch.

**To Reproduce**
Launch and then close RimWorld, then look at ModsConfig.xml. Mine is below.
```
<?xml version="1.0" encoding="utf-8"?>
<ModsConfigData>
  <version>1.5.4069 rev95</version>
  <activeMods>
    <li>brrainz.harmony</li>
    <li>ludeon.rimworld</li>
    <li>nightmare.jaxe.publisherplusmultiversionfork</li>
    <li>broms.reloadmods</li>
    <li>mlie.showmodupdates</li>
  </activeMods>
  <knownExpansions>
    <li>ludeon.rimworld.royalty</li>
    <li>ludeon.rimworld.ideology</li>
    <li>ludeon.rimworld.biotech</li>
  </knownExpansions>
</ModsConfigData>
```
Launch RimSort, save the mod list, then look at ModsConfig.xml again. Notice that the two mentioned nodes are no longer present.
```
<?xml version="1.0" encoding="utf-8"?>
<ModsConfigData>
	<activeMods>
		<li>brrainz.harmony</li>
		<li>ludeon.rimworld</li>
		<li>nightmare.jaxe.publisherplusmultiversionfork</li>
		<li>broms.reloadmods</li>
		<li>mlie.showmodupdates</li>
	</activeMods>
</ModsConfigData>
```
Launch RimWorld and open the mod list. See that the owned expansions have been added to the bottom of the mod list. ModsConfig.xml has also been changed to add back the missing data.
```
<?xml version="1.0" encoding="utf-8"?>
<ModsConfigData>
  <version>1.5.4069 rev95</version>
  <activeMods>
    <li>brrainz.harmony</li>
    <li>ludeon.rimworld</li>
    <li>nightmare.jaxe.publisherplusmultiversionfork</li>
    <li>broms.reloadmods</li>
    <li>mlie.showmodupdates</li>
    <li>ludeon.rimworld.royalty</li>
    <li>ludeon.rimworld.ideology</li>
    <li>ludeon.rimworld.biotech</li>
  </activeMods>
  <knownExpansions>
    <li>ludeon.rimworld.royalty</li>
    <li>ludeon.rimworld.ideology</li>
    <li>ludeon.rimworld.biotech</li>
  </knownExpansions>
</ModsConfigData>
```

**Expected behavior**
Only the `activeMods` node should be changed.

**Screenshots**
Mod list as saved in RimSort
![Screenshot 2024-04-25 094333](https://github.com/RimSort/RimSort/assets/78392890/d3400040-da0e-4935-81c7-89e8b2fc6e61)
Mod list shown in game
![Screenshot 2024-04-25 094340](https://github.com/RimSort/RimSort/assets/78392890/b7f893fd-8f43-4e3a-845d-5f205feef1c2)

**Please complete the following information:**
 - OS: Windows 10
 - RimSort version: Alpha-v1.0.6.2-hf [Edge 6db22ad]
 - Please provide a `RimSort.log`: https://0x0.st/XHmG.log
 - Are you running from Python interpreter or from a compiled RimSort release? Compiled Edge release

**Comment by twstagg** [comment]
Fixed in branch `instancing`

**Comment by divineDerivative** [comment]
The contents of the `knownExpansions` tag is still being removed.

```
<?xml version="1.0" encoding="utf-8"?>
<ModsConfigData>
	<version>1.5.4104 rev435</version>
	<activeMods>
		<li>brrainz.harmony</li>
		<li>ludeon.rimworld</li>
		<li>rswallen.devpaletteprofiles</li>
		<li>nightmare.jaxe.publisherplusmultiversionfork</li>
		<li>broms.reloadmods</li>
	</activeMods>
	<knownExpansions>
	</knownExpansions>
</ModsConfigData>
```

**Comment by TheRealElysium** [comment]
Just wanted to add to this.  I have recently started a game without anomaly.  Every time I sort my modlist with RimSort while anomaly is disabled, it will remove the _<li>ludeon.rimworld.biotech</li>_ entry from **ModsConfig.xml**

While RimSort shows anomaly disabled in the disabled column list, this is changed upon launching Rimworld.  If you have installed DLCs that are not in **ModsConfig.xml**, Rimworld will automatically repopulate the list with the missing DLCS included.  

Now, I don't know the specifics of why that is happening, but I do know that if I manually change this:
`	<knownExpansions>
		<li>ludeon.rimworld.royalty</li>
		<li>ludeon.rimworld.ideology</li>
		<li>ludeon.rimworld.biotech</li>
	</knownExpansions>`

to this:
	<knownExpansions>
		<li>ludeon.rimworld.royalty</li>
		<li>ludeon.rimworld.ideology</li>
		<li>ludeon.rimworld.biotech</li>
		<li>ludeon.rimworld.anomaly</li>
	</knownExpansions>
	
in **ModsConfig.xml** after sorting my modlist with RimSort, rimworld launches with anomaly disabled as expected.

**Comment by hk21702** [comment]
I'll try to focus on this next since it seems like a fairly critical issue that can't wait for a full metadata rework.
