### ISSUE TITLE
FIXME: Crash when dragging two or more mods from "inactive" to "active"

### ISSUE THREAD

**Issue by 114119** [RimSort/RimSort#312]
**Describe the bug**
Crash when dragging two or more mods from "inactive" to "active"

**To Reproduce**
1. Mark 2 mods in "inactive" tab with either shift or ctrl
2. Drag to "active"
3. See popup with error:
```
Traceback (most recent call last):
  File "C:\Games\rimworld\RimSort\app\views\mods_panel.py", line 1513, in handle_rows_inserted
TypeError: 'NoneType' object is not subscriptable
```

**Expected behavior**
No crash and mods added to active

**Please complete the following information:**
 - OS: Win11
 - RimSort version: Rimsort Alpha-v1.0.6.2-hf [Edge 699c45e]
 - Please provide a `RimSort.log`: https://0x0.st/XHkW.old.log
 - Are you running from Python interpreter or from a compiled RimSort release? Compiled, RimSort-Edge_699c45e_Windows_x86_64.zip

**Comment by 114119** [comment]
Actually seems to happen with even just one mod selected - it worked earlier.

**Comment by 114119** [comment]
Just tried to restart it once more. The app didn't show this time. I found the process in task manager and killed it. The app started but no error this time. 

I'll do the above steps if it happens again.

**Comment by LionelColaso** [comment]
Thanks, feel free to reopen this issue if it happens again
