### ISSUE TITLE
FIXME: RimSort appears to not use/notice Load After rule By Version

### ISSUE THREAD

**Issue by quianalevitt** [RimSort/RimSort#314]
**Describe the bug**
<img width="678" alt="image" src="https://github.com/RimSort/RimSort/assets/92599443/75263706-2e40-405e-b77f-48ad0eea854a">
Appears that the RimSort isn't noticing or using the Load After tag when it's done by version.

**To Reproduce**
Check Research Reinvented: Stepping Stones, perfect example, load after by version for VE: Tribals

**Expected behavior**
Should sort it below Tribals as per rule.

**Please complete the following information:**
 - OS: Windows (N/A for bug)
 - RimSort version: Edge 699c45e
 - Please provide a `RimSort.log`: http://0x0.st/XXze.log
 - Compiled Edge release as above

**Comment by twstagg** [comment]
@quianalevitt Are you able to test and confirm?

**Comment by quianalevitt** [comment]
I can confirm that it is now sorting appropriately, but I can also indicate that there isn't any visual display of the sort rule by version unless you sort a mod out of order:
![image](https://github.com/RimSort/RimSort/assets/92599443/82e63c07-8685-456e-bfba-8e4d33ce9aee)
