### ISSUE TITLE
FIXME: Rimsort packaged builds unable to launch on MacOS

### ISSUE THREAD

**Issue by Limfjorden** [RimSort/RimSort#323]
**Describe the bug**
Rimsort does not launch. Instead, a pop-up explains that rimsort crashed.

**To Reproduce**
1. Download [rimsort](https://github.com/RimSort/RimSort/releases/tag/Edge)
2. Unzip the file
3. Move the created App to Applications
4. Open terminal
5. run `cd Applications`
6. run `xattr -d com.apple.quarantine RimSort.app` (this is to stop gatekeeper preventing launch)
7. try to open Rimsort, by double-clicking on it

**Expected behavior**
Rimsort can be launched after having done step 6 above.

**Please complete the following information:**
 - OS: macOS Ventura 13.6.6
 - Processor: 3,4 GHz Quad-Core **Intel** Core i5
 - RimSort version: [Rimsort Edge cdcf1a8](https://github.com/RimSort/RimSort/releases/tag/Edge)
 - Apple's crash log: ```Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @executable_path/Python
Referenced from: <96E7ADD6-83FB-30E1-9E9C-CC973164BEA7> /Users/USER/Downloads/RimSort.app/Contents/MacOS/RimSort
Reason: tried: '/Users/user/Downloads/RimSort.app/Contents/MacOS/Python' (no such file), '/usr/local/lib/Python' (no such file), '/usr/lib/Python' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)```
 - I am running a pre-compiled release.

**Comment by Chunnyluny** [comment]
Can you maybe try to get python 3.11.9 instead? and let us know what happens then

**Comment by twstagg** [comment]
> Can you maybe try to get python 3.11.9 instead? and let us know what happens then

Chunny,

This is a nuitka issue. They wouldnt be here with this issue if they were running from a development environment. We should probably avoid suggesting these things to people unless they are interested in contributing code or working on a technical issue.

**Comment by Chunnyluny** [comment]
> > Can you maybe try to get python 3.11.9 instead? and let us know what happens then
> 
> Chunny,
> 
> This is a nuitka issue. They wouldnt be here with this issue if they were running from a development environment. We should probably avoid suggesting these things to people unless they are interested in contributing code or working on a technical issue.

NVM then, but my Rimsort also said it couldn't find python, but python was installed --> 3.11.6 after I installed 3.11.9 it didn't give the warning any more.

**Comment by metocolipson1** [comment]
I am having the same issue. I have a completely updated Mac.

**Comment by twstagg** [comment]
Possibly related? https://github.com/Nuitka/Nuitka/issues/789#issuecomment-774737373

**Comment by Limfjorden** [comment]
Issue still present on [Edge cdcf1a8](https://github.com/RimSort/RimSort/releases/tag/Edge).

**Comment by hk21702** [comment]
Just for documentation reasons, this is due to this issue https://github.com/Nuitka/Nuitka/issues/2853 and a misconfiguration in github's mac 13 runners involving the brew lib openssl@3. It should be currently fixed for edge, and in the future, the build workflow will be updated so that it'll catch errors similar to this and make it more obvious that something is wrong.
