### ISSUE TITLE
FIXME:  RimSOrt crash when clicking on either Build Database, SteamCMD or Steam button

### ISSUE THREAD

**Issue by ezadEzanee** [RimSort/RimSort#324]
**Describe the bug**
RimSOrt crash when clicking on either Build Database, SteamCMD or Steam button. 

Traceback (most recent call last):
  File "/Applications/RimSort.app/Contents/MacOS/app/views/main_content_panel.py", line 3142, in _on_do_build_steam_workshop_database
  File "/Applications/RimSort.app/Contents/MacOS/app/views/main_content_panel.py", line 2614, in _do_build_database_thread
NameError: name 'GameConfiguration' is not defined

**To Reproduce**
Please refer to screenshot

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - RimSort version:
 - Please provide a `RimSort.log`: http://0x0.st/X8u2.log
 - Are you running from Python interpreter or from a compiled RimSort release?

**Additional context**
![CleanShot - RimSort - RimSort Alpha-v1 0 6 2-hf  Edge af0eae1  - 2024-05-09 at 01 11 42](https://github.com/RimSort/RimSort/assets/18095325/54b8ae5e-0bc0-4252-83d8-51b5e9601c43)

**Comment by ezadEzanee** [comment]
http://0x0.st/X8ut.old.log

WIth debug turned on

**Comment by cebarks** [comment]
I'm also running into this issue on Fedora 40.

**Comment by twstagg** [comment]
This should be fixed now.
