### ISSUE TITLE
Suggestion: Warning when Steam isn't Launched

### ISSUE THREAD

**Issue by hk21702** [RimSort/RimSort#340]
**Is your feature request related to a problem? Please describe.**
When steam is not launched for certain functions that require steam, the rimsort does not notify the user in an obivous manner. When a check does occur, it is logged in the logs if it fails, but there isn't anything else. 

**Describe the solution you'd like**
A popup warning if rimsort detects that steam is not launched. Optionally can override this warning for applications where steam is optional, such as launching the game itself. Something similar to how MO2 works if you are familiar with that. 

I believe that currently a check is implemented for some functions like workshop mod updates, but not for stuff like launching the game itself. While running rimworld with steam is optional, it would be nice to have a warning. If need be, add a setting to disable this warning in case, for whatever reason, your rimworld copy is not from steam, or you don't care if steam is running.

**Additional context**
I'm willing to work on this and make a pull request, just opening issue for discussion purposes.

**Comment by twstagg** [comment]
This should be resolved with Instancing and the toggle for "Steam client integration" under Settings -> Advanced in v1.0.7
