### ISSUE TITLE
Suggestion: Update Wiki

### ISSUE THREAD

**Issue by hk21702** [RimSort/RimSort#344]
This issue is to monitor what changes to the wiki as well as other documentation that should be done. There are some updates to the wiki (and read me) that should be made. Please don't hesitate to contribute and make pull requests!

- [x] General
  - [x] Fix style and linting issues of .md files
  - [x] Add repo about

- [ ] Wiki Related
  - [x] Home
  - [x] FAQ Section
  - [x] Development Guide
    - [x] Remove references to RimSort.py
    - [x] Update manual build section?
  - [ ] User Guide
    - [ ] Updating screenshots

**Comment by Limfjorden** [comment]
We should also add an FAQ section with solutions to common problems, such as how to whitelist the app on macOS, where the path settings are located, what the community DB and what the steam DB is. Each answer could be a custom text, or just a link to the main text in the user/developer guide. If we then prominently link to this FAQ on discord, I think this would eliminate a lot of people posting about problems, that have already been solved once before.

**Comment by Limfjorden** [comment]
@hk21702 I've made the FAQ section on [my fork](https://github.com/Limfjorden/RimSort/wiki). Direct git link for ease of merging: https://github.com/Limfjorden/RimSort.wiki.git

**Comment by hk21702** [comment]
@Limfjorden Sorry for taking so long. It should be merged. I've also added some minor spelling and formatting fixes.

**Comment by Limfjorden** [comment]
@hk21702 I got a new screenshot for the mac preview right here:
<img width="1136" alt="billede" src="https://github.com/RimSort/RimSort/assets/66277585/41e3be83-7599-45d0-a117-3d89d11d2fb9">

**Comment by hk21702** [comment]
Mostly just need to update the media assets at this point to get things into a good state.
