### ISSUE TITLE
FIXME: Rimsort crash when adding a large collection to the download list

### ISSUE THREAD

**Issue by Waklaidan** [RimSort/RimSort#349]
**Describe the bug**
When I add a large collection to the download list, Rimsort crashes
This is exactly what happened with this collection.
For example, this collection caused this problem https://steamcommunity.com/sharedfiles/filedetails/?id=3187121098
**To Reproduce**
1. Select any collection with big amount of mods
2. Click on Add to list
3. Rimsort crashes

**Expected behavior**
Rimsort does not crash and downloads the collection normally

**Please complete the following information:**
 - OS: Windows 11
 - RimSort version:1.0.6.2-hf
 - Please provide a `RimSort.log`: http://0x0.st/XPwY.log
 - Compiled version from releases table

**Additional context**
Traceback after crash
```Traceback (most recent call last):
  File "C:\Users\marcus\RimSort\app\utils\steam\browser.py", line 187, in _add_collection_or_mod_to_list
  File "C:\Users\marcus\RimSort\app\utils\steam\browser.py", line 235, in __compile_collection_datas
KeyError: 'title'
```

**Comment by LionelColaso** [comment]
it loads perfectly uptill here is the error after this screen ? or it doesnt load tjhis screen for you ?
also do you have steam database enabled or disabled ?

![image](https://github.com/RimSort/RimSort/assets/2488703/9eb7a65a-2d9e-4df6-98b4-76e233f9eaf0)

**Comment by LionelColaso** [comment]
> It crashes a few seconds after clicking add to list, showing no other windows except the Traceback window SteamDb is disabled, but I think it doesn't affect in this case

between can you try importing this way by adding the link 
![image](https://github.com/RimSort/RimSort/assets/2488703/e897242c-6bde-4503-a18d-c55976fe61e5)

**Comment by LionelColaso** [comment]
ok replicated your issue will fix soon

**Comment by LionelColaso** [comment]
pushed fix https://github.com/RimSort/RimSort/pull/350/commits/e53c010a407eba69a2467b7b5d8721670c2ccbfc

in the mean while to download collection use https://github.com/RimSort/RimSort/issues/349#issuecomment-2120982295

**Comment by LionelColaso** [comment]
> When this commits will be pushed to main branch?

maybe in some hours depends
