### ISSUE TITLE
FIXME: Crashed while downloading collection from steam workshop

### ISSUE THREAD

**Issue by Waklaidan** [RimSort/RimSort#355]
**Describe the bug**
Title

**To Reproduce**
1. Go to Workshop download
2. Start downloading large collection
3. Wait
4. Crashed

**Expected behavior**
Doesn't crash

**Screenshots**

**Please complete the following information:**
 - OS: win 11
 - RimSort version: latest commit c76e96c
 - Please provide a `RimSort.log`: http://0x0.st/XZsa.log
 - I compiled it myself via github actions

**Additional context**
Traceback (most recent call last):
  File "C:\Users\marcus\Desktop\rsort\app\views\mods_panel.py", line 2127, in on_mod_created
  File "C:\Users\marcus\Desktop\rsort\app\views\mods_panel.py", line 1480, in append_new_item
  File "C:\Users\marcus\Desktop\rsort\app\views\mods_panel.py", line 1467, in resizeEvent
  File "C:\Users\marcus\Desktop\rsort\app\views\mods_panel.py", line 1515, in check_widgets_visible
  File "C:\Users\marcus\Desktop\rsort\app\views\mods_panel.py", line 1491, in create_widget_for_item
TypeError: 'NoneType' object is not subscriptable

**Comment by LionelColaso** [comment]
can you provide link to which workshop collection you were downloading ?

**Comment by LionelColaso** [comment]
> > can you provide link to which workshop collection you were downloading ?
> 
> same https://steamcommunity.com/sharedfiles/filedetails/?id=3187121098

i cant seem to replicate your issue 

Uploading nocrash.mp4…

**Comment by LionelColaso** [comment]
> > nocrash.mp4
> > > > can you provide link to which workshop collection you were downloading ?
> > > 
> > > 
> > > same https://steamcommunity.com/sharedfiles/filedetails/?id=3187121098
> > 
> > 
> > i cant seem to replicate your issue
> 
> I am downloading collection via Add to list from Browse Workshop menu

yeah you can see the video i did the same ?

**Comment by LionelColaso** [comment]
> > > > nocrash.mp4
> > > > > > can you provide link to which workshop collection you were downloading ?
> > > > > 
> > > > > 
> > > > > same https://steamcommunity.com/sharedfiles/filedetails/?id=3187121098
> > > > 
> > > > 
> > > > i cant seem to replicate your issue
> > > 
> > > 
> > > I am downloading collection via Add to list from Browse Workshop menu
> > 
> > 
> > yeah you can see the video i did the same ?
> 
> Sorry, I didn't notice



can you enable debugging in settings and restart RimSort and Recreate the issue and upload log

**Comment by LionelColaso** [comment]
fixed in https://github.com/RimSort/RimSort/commit/74fbe106f2dc10e7761652053a7a5f61bb999537
