### ISSUE TITLE
FIXME: "'RimSort' is damaged and can't be opened."

### ISSUE THREAD

**Issue by AlexaDiNicola** [RimSort/RimSort#361]
**Describe the bug:** Exactly what it says on the tin. The current MacOS release won't open at all on my machine: the OS is convinced that the file is somehow modified or damaged, and refuses to open it.

**To Reproduce**
1. Download the MacOS Intel 1.0.7 release (RimSort-v1.0.7-Darwin_i386.zip) and unzip it.
2. Double-click on the app icon.
3. See error: "'RimSort' is damaged and can't be opened. You should move it to the Trash. / Chrome downloaded this file today at 11:50 AM."

**Please complete the following information:**
 - OS: MacOS Sonoma 14.4.1
 - RimSort version: 1.0.7
 - Please provide a `RimSort.log`: RimSort won't start, much less log anything AFAIK. Instead, see [this MacOS Console log excerpt](https://github.com/RimSort/RimSort/files/15437793/logs-2024-05-24.txt) of what happens when I try to open the app. (Please also let me know if there are other logs I could provide as well.) 
 - Running from a compiled release

**Additional context**
Not sure if any of the following is relevant, but I first tried to open RimSort before even subscribing to the RimPy Database mod. After getting this error for the first time, I deleted the app, subscribed to the mod, re-downloaded the app, unzipped it again, and tried again. Same error -- nothing apparently changed. RimWorld was running at the time (not in-game, just open), so I quit the game, deleted the app, unzipped it again (same download this time), and tried again. Still no change.

**Comment by hk21702** [comment]
This is covered in the user guide of the wiki.

https://github.com/RimSort/RimSort/wiki/User-Guide#macos
