### ISSUE TITLE
FIXME: App crash when creating instance

### ISSUE THREAD

**Issue by SierraKomodo** [RimSort/RimSort#364]
**Describe the bug**
When creating a new instance, the app crashes.

**To Reproduce**
1. Go to 'Instances > Create Instance'
2. Enter any name for the new instance (Tried with `Single Player`, `Singleplayer`, `singleplayer`)
3. Click 'OK'

**Expected behavior**
A new instance should be created without crashing or, if this is a user error problem, it should present an error message for the user correct instead of crashing,

**Screenshots**
![RimSort_IFA8Lk3OJR](https://github.com/RimSort/RimSort/assets/11140088/a71a4d30-f265-4fc0-bc6f-a391d5872c0a)

**Please complete the following information:**
 - OS: Windows 10 Build 19045 64-bit
 - RimSort version: 1.0.7
 - Please provide a `RimSort.log`: [RimSort.log](https://github.com/RimSort/RimSort/files/15440992/RimSort.log)
 - Compiled release

**Additional context**
**NOTE**: This does have a collection of local mods indexed that were previously installed and managed using RimPy. Unsure if that may have any effect here or not.

```
Traceback (most recent call last):
  File "G:\Modding\RimSort\app\views\main_window.py", line 745, in __create_new_instance
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by hk21702** [comment]
@twstagg To be honest, this might be the scenario I was referring to with the none typing and stripping.
