### ISSUE TITLE
Update for AMD Machines

### ISSUE THREAD

**Issue by Cryothing** [RimSort/RimSort#368]
Rimsort shows me that there is a new Update available.

Whan i click Update, i get the following error message:

Failed to find valid Rimsort release for Windows 64bit AMD 64 Familiy 25 Model 33 stepping 2 Authentic AMD

**Screenshots**
![Screenshot 2024-05-25 144935](https://github.com/RimSort/RimSort/assets/170807454/70c84607-3ce0-4d15-bdfc-c93ad14ae5f1)

**Please complete the following information:**
 - OS: Windows 11
 - RimSort version:
 - Please provide a `RimSort.log`: 
[RimSort.log](https://github.com/RimSort/RimSort/files/15443498/RimSort.log)

 - Are you running from Python interpreter or from a compiled RimSort release?
 - Compiled Rimsort Release

**Comment by LionelColaso** [comment]
you have to manually install RimSort Updates Auto updates are disabled currently

**Comment by Cryothing** [comment]
oh, i dint knew that auto update doesnt work. thanks, i updated it.
