### ISSUE TITLE
FIXME: RimSort crashes when dragging active mods into an inactive list

### ISSUE THREAD

**Issue by windicevista** [RimSort/RimSort#371]
**Describe the bug**
RimSort crashes when dragging active mods into an inactive list

**To Reproduce**
1.Dragging nearly 15+ mods from "Active" to "Inactive"

**Expected behavior**
Drag the module from "Active" to "Inactive" and Save

**Screenshots**
![image](https://github.com/RimSort/RimSort/assets/7019719/be3d3ce7-8e80-435b-8779-9d65a5ccd1be)

**Please complete the following information:**
 - OS: Windows 10
 - RimSort version: v1.0.7
 - Please provide a `RimSort.log`:[RimSort.log](https://github.com/RimSort/RimSort/files/15445468/RimSort.log)
 - Running from a compiled release

**Comment by Limfjorden** [comment]
Isn't this the same issue as https://github.com/RimSort/RimSort/issues/327
