### ISSUE TITLE
FIXME: Dubs Mint Menu Research UI Broken

### ISSUE THREAD

**Issue by aztecrabbit** [RimSort/RimSort#375]
**Describe the bug**
Dubs Mint Menu Research UI Broken when sorting using "Sort active mods". Fixed when Dubs Mint Menu moved to very bottom (Above RocketMan, More Planning, etc), don't know what mod that causing this issue, mod list, [27-05-2024.xml.log](https://github.com/RimSort/RimSort/files/15455736/27-05-2024.xml.log)

**Please complete the following information:**
 - OS: Arch Linux
 - RimSort version: alpha-v1.0.6.2-hf
 - Please provide a `RimSort.log`: -
 - Are you running from Python interpreter or from a compiled RimSort release? from AUR, `rimsort-bin`

**Comment by Limfjorden** [comment]
This is just a load-order issue, not an issue with the app itself. Open a PR for the [CR DB](https://github.com/RimSort/Community-Rules-Database) so Rimsort can sort more mods more better.
