### ISSUE TITLE
Application not opening on Pop!_Os 22.04 LTS

### ISSUE THREAD

**Issue by HopeCaldwell** [RimSort/RimSort#383]
Description of the bug:

1. Try to open RimSort on Pop!_Os 22.04 LTS
2. Nothing happens

Expected behavior:
App opening, or at least the logs having something in them.

OS: Linux
Distro: Pop!_Os 22.04 LTS,      (based on ubuntu)
 RimSort version: 1.0.7
I am running from the compiled version of the app.
Logs are empty.

[RimSort.log](https://github.com/user-attachments/files/15521507/RimSort.log)
[RimSort.old.log](https://github.com/user-attachments/files/15521508/RimSort.old.log)

**Comment by hk21702** [comment]
This is rather tricky given that there are no logs. Can you try running the application using the command line? See if any logs show up if you do so?

**Comment by HopeCaldwell** [comment]
![image](https://github.com/RimSort/RimSort/assets/171423586/a2c46730-0bbf-43a2-8435-cba94ff809e4)
it turns out that the problem was on my side, and I was missing some files, it is solved now, thanks for your help.
