### ISSUE TITLE
Suggestion: Add sanity checks before rm -rf

### ISSUE THREAD

**Issue by CoatMcMutton** [RimSort/RimSort#396]
OS: Linux Manjaro

Problem: After a separate issue caused RimSort to be unable to launch, I tried to run update.sh via terminal. Didn't check the file contents, just gave it permission to execute, didn't cd into RimSort root directory first, resulting in an attempted run of rm -rf on my home directory.

Proposal: Before running rm -rf, first confirm that the directory to be nuked actually contains the RimSort file. If it's missing, tell the user to delete the folder and reinstall from scratch manually.

**Comment by hk21702** [comment]
The entire update regime right now is slated to be remade. To be honest, we probably shouldn't include the update files until then.
