### ISSUE TITLE
FIXME: Crash when adding enough mods to the active/inactive section to cause the scrollbar to show up, crash on Database builder command, crash on local to workshop migration.

### ISSUE THREAD

**Issue by Raizanad** [RimSort/RimSort#399]
I know that it would be better to split this bug report but I don't have the time.

**Describe the bug:**
Several crashes on 3 different matters that are likely related. Each number below will correlate with the report/reproduction below.
1. Overflow changing of the active/inactive section.
2. Database building.
3. Local to workshop mod migration.
4. Adding mods to the mod folder while the manager is open.
5. Downloading mods in quick succession via steamCMD.
6. There is also a duplication/triplication problem happening when adding mods from a collection with SteamCMD. It goes away after forcing a sort but it is tedious.

**To Reproduce:**
1:
A. With the active or inactive section having no scrollbar move enough mods click drawing them to the opposite section to cause the scroll bar to show.
B. Error will show: 
```
Traceback (most recent call last):
  File "E:\Games\Ludeon\RimSort\app
\views\mods_panel.py", line 1038, in eventFilter
```

2.
A. Click build database.
B. It will finish the process but no DB will be built because the following error will show just at the end:
```
Traceback (most recent call last):
  File "E:\Games\Ludeon\RimSort\app\utils\metadata.py", line 2072, in run
  File "E:\Games\Ludeon\RimSort\app\utils\steam\webapi\wrapper.py", line 260, in create_steam_db
  File "E:\Games\Ludeon\RimSort\app\utils\steam\webapi\wrapper.py", line 589, in ISteamUGC_GetAppDependencies
TypeError: 'NoneType' object is not iterable
```
[SteamCMD DB Build.txt](https://github.com/user-attachments/files/15699316/SteamCMD.DB.Build.txt)

3.
A. Try to migrate any mod from local to workshop.
B. Error will show:
```
Traceback (most recent call last):
  File "E:\Games\Ludeon\RimSort\app\views\mods_panel.py", line 1038, in eventFilter
  File "E:\Games\Ludeon\RimSort\pathlib.py", line 871, in __new__
  File "E:\Games\Ludeon\RimSort\pathlib.py", line 509, in _from_parts
  File "E:\Games\Ludeon\RimSort\pathlib.py", line 493, in _parse_args
TypeError: expected str, bytes or os.PathLike object, not dict
```

4.
A. Add several mods by drawing the into the mod folder.
B. Manager will crash with an error that I may edit below later.

5.
A. Same as 4, but I think it happens when SteamCMD updates/downloads too many mods too fast.
B. Hard to reproduce even for me since SteamCMD is slow but if it happens I will update this. It has happened 5 times today but it is when importing long collections.

**Expected behavior:**
For all the errors the expected behavior is obvious. But there is one that is interesting:
4. Shoulld be fixed, but it shouldn't ever happen if the app behavior was to use the refresh button to catch new mods. It is constantly monitoring the mod folder instead.

**Please complete the following information:**

- OS: Windows 11
- RimSort version: 1.0.8 (Also used 1.0.9 and can assure that 1, 2 and 3 happen there too)
- Are you running from Python interpreter or from a compiled RimSort release?
Directly downloaded from the github for windows.

**Comment by Raizanad** [comment]
Additional context on 1, since I just saw 2 other open issues on the topic.
It happens on a fresh install (never used before) RimSort. Once you circumvent the problem via resizing the window, save/loading mods and so on then it stops happening all together apparently. It still is an issue and it is linked to 3 I believe.

**Comment by hk21702** [comment]
Will investigate this, though may take a while since I'm doing a complete rework of how metadata is handled currently

**Comment by Raizanad** [comment]
I have been using the app extensively and need to ask for a bunch of features. Thanks for your work.

**Comment by Raizanad** [comment]
Closing as issue one in the list is probably fixed, and the rest have their own tracking now.
