### ISSUE TITLE
Mods not loading in game. [Solved]

### ISSUE THREAD

**Issue by Fuedra** [RimSort/RimSort#407]
So I decided to move over to this mod manager as I I have been hearing this is better at handling Rimworld mods, but I have run into a problem.

Now I initially had a hiccup getting things set up, but was able to figure it out, but now I am running into a problem. After copying over my mod list and hitting sort, I hit run, start reading a book as I know it will take a while for my mod list to load, and then become surprised as the game loads up insanely fast. So I check the mod tab, and I notice that according to that none of the mods that are shown as activated in Rimsort are active in game.

I have no idea how to fix this, as I don't know what could be causing this issue, so if anyone has any ideas, please let me know.

Update:
Tried clearing the list and adding only one mod, does not show up in game, and that mod did not show up, tired saving my list, and reloading it, mods still do not show up. Have tried sorting and saving the mods list multiple times, but the mods still do not show up.  I am going to try re-installing the program, but if this happens again I will be at a loss for what to do.

Update 2:
Tried reinstalling the entire program, but still nothing, whether I load my list or I load one mod, then hit sort and save, after hitting run it boots the game up as if no mods are activated. Unless I can find a solution to this problem, I am just going to have to go back to Rimpy as it still works.

Update 3:
Ok, noticed something odd, so not only does it not load any of the mods I have listed as activated, it also loaded up the game as if it was the first time I ever ran Rimworld, so none of the settings that I had modified were as I had left them.

Also, I just tried to use the pre-release version of Rimsort to see if maybe it was just the version I was using, but no, the no mods activated problem still persists.

Update 4:
Ok its official now, Rimsort is not effecting my mod list in anyway no matter how I change it, for I just enabled a mod with Rimsort, went through the standard process, then hit run. Game booted up, saw that the mod showed as not activated, and then decided to test an idea, so I enabled the mod in the games mod tab, restarted the game, saw that the mod was activated, then I quit, deactivated the mod in Rimsort, sorted, saved and then ran the game, and when it booted up and I went into the mods tab there the mod was, even though I had deactivated the mod in Rimsort.

Update 5:
Ok, so I did some testing, and I found out that for whatever reason, Rimsort unlike Rimpy is not accepting anything from the config folder that I selected for it that's on my D drive, instead its acting like that folder doesn't exist and defaulting to the C drive local folder, which has nothing in it.

I am going to try and copy everything from my D drive folder into the C drive folder, but if that doesn't work I'll be back to square one again.

Solved:
So as it turns out, Rimsoft will not accept a config folder location anywhere but the one created in the LocalLow folder of AppData, and if you try to have it set to any folder other then that one, the game will just default to the folder in LocalLow and ignore the config folder you designated, meaning it will act as if you haven't activated any mods.

**Comment by LionelColaso** [comment]
You have to Click "Save" after "Sort" to save your changes else the modlist wont be saved and wont be loaded by the Game

**Comment by Fuedra** [comment]
I did that, even after hitting save when I hit run, the game loads up, I get a few seconds with the small loading box, and then it goes quickly into loading defs, then into initializing before it boots into the main menu, and when I look at the mods tab it shows that none of my mods are activated.
