### ISSUE TITLE
Suggestion: Run fullscreeen windowed (pass parameters to run button)

### ISSUE THREAD

**Issue by 97Cweb** [RimSort/RimSort#409]
**Is your feature request related to a problem? Please describe.**
I get frustrated with RimSort compared to RimPy for 1 reason only, In RimPy, I can click run, and it will launch in borderless mode, allowing for alt tab onto a second screen without minimizing. This is achieved by passing "-popupwindow" in the run command.

I would like an option to add this command to the run, without having to launch through steam. RimPy has it, so it is feasible.

I currently usually forget, but when I do remember, I have to launch from the steam client. Not game breaking but annoying

**Comment by Raizanad** [comment]
![image](https://github.com/RimSort/RimSort/assets/131222736/59a29e17-929c-42a7-b930-ac5b8e9ae33a)

**Comment by 97Cweb** [comment]
Thank you for that! Might want it more obvious
