### ISSUE TITLE
Suggestion: support mod "fill-ins"

### ISSUE THREAD

**Issue by oceancabbage** [RimSort/RimSort#418]
Some mods (like Prepatcher: https://steamcommunity.com/workshop/filedetails/?id=2934420800) can replace other mods (e.g. Harmony) and can also be loaded together. So, we shouldn't be showing errors if only Prepatcher is loaded but Harmony isn't. All other mods that depend on Harmony are not expected to add a dependency on Prepatcher in addition to Harmony though, so it's up to us to come up with some sort of mapping solution to support these cases.

**Comment by oceancabbage** [comment]
Will be fixed through: https://github.com/RimSort/RimSort/pull/424

**Comment by Limfjorden** [comment]
@oceancabbage Can you make the PR automatically close this?

**Comment by hk21702** [comment]
Its actually already merged so can just close this.
