### ISSUE TITLE
Suggestion: Implement anonymized logs

### ISSUE THREAD

**Issue by Limfjorden** [RimSort/RimSort#427]
**Is your feature request related to a problem? Please describe.**
When using the "upload log" functionality, RimSort will upload your log as is. This can expose your username on the computer, which for some people is their real name.

**Describe the solution you'd like**
A solution to this issue is for RimSort to automatically detect the user name and replace it with "user" before uploading the log. Or, if automatic detection is not an option, the user could fill in their username and rimsort could find-and-replace the log for that.

As an example, RimSort would see: 
`/Users/john_smith/Library/Application Support/Steam/steamapps/common/Rimworld/RimworldMac.app/Data`/

and replace it with this:
`/Users/user/Library/Application Support/Steam/steamapps/common/Rimworld/RimworldMac.app/Data/`

All instances of `john_smith` would be replaced with `user`.

**Describe alternatives you've considered**
This is suggestion is obviously a big task, so a more feasible alternative could be to make it crystal clear to the user, that the uploaded log will have their username in it, so they can redact it themselves. Redaction can easily be done with find and replace in a text editor. This should probably be a confirmation pop-up with an option to cancel the upload.

**Additional context**
I would not consider this a high priority suggestion. 

**Tags:** Security

**Comment by hk21702** [comment]
Implemented in #432
