### ISSUE TITLE
FIXME: Crash when overflow state changes in the active/inactive mod section.

### ISSUE THREAD

**Issue by Raizanad** [RimSort/RimSort#447]
This was already reported on #399 by me. I'm just separating the issues within that report for better tracking and also closing that report once done.
Also, for tracking and closing of issues when the problem gets fixed: #327 and #371 are about the same thing:

Crash when overflow state changes in the active/inactive mod section - at least on RimSort clean slate states (i.e. when the window on startup has insufficient mods to cause the scroll bar to show up).
Can be circumvented by expanding the App window, dropping mods into the column then resizing.

To Reproduce:
1: With the active or inactive section having no scrollbar move enough mods click drawing them to the opposite section to cause the scroll bar to show.

**Comment by hk21702** [comment]
This should be already fixed in the latest edge release via PR #429.

I'm going to close the issue for now, but if it persists, feel free to reopen it. Also, for the future, just add additional context to the existing issues. No need to make a duplicate.
