### ISSUE TITLE
FIXME: This application failed to start because no Qt platform plugin could be initialized.

### ISSUE THREAD

**Issue by EpiChrist** [RimSort/RimSort#461]
**Describe the bug:**
I try to launch the program, and nothing happen. The log says the program could not load the Qt Platform plugin xcb, so, I also try to install the xcb plugin. And the same problem still arrive.

**To Reproduce:**

1. Launch the program... I guess?

**Please complete the following information:**

- Operating System: Ubuntu 22.04.4
- Processor Architecture: 64 bits
- RimSort version: 1.0.8
- Please provide a `RimSort.log`:
Don't have any, or I don't know where it is.

Nevertheless, here the only «log» I have :
   qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
   qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
   This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

   Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.

   Abandon (core dumped)

**Checklist before opening issue:**

- **Did you check the wiki for a solution?** 
- Yes.
- **Did you make sure this issue wasn't already reported?**
- Yes and I don't think there is...

**Comment by angiioh** [comment]
Happening to me as well. I'm on Linux Mint 21.3

**Comment by hk21702** [comment]
Some distros are missing some system libraries needed for QT. I don't think there is anything we can really do other than better document this? May be able to maybe try and add a check and apt-get if it is missing. 

For our own Github test workflows, we install libegl-dev though for that test environment there is no graphics. You are going to need to just follow the instructions that are given in the error settings. In your case, it is saying that it needs xcb-cursor0/libxcb-cursor0. These are extra libs that aren't included within xcb by itself so you need to install them separately. 

Based on this post https://stackoverflow.com/questions/77725761/from-6-5-0-xcb-cursor0-or-libxcb-cursor0-is-needed-to-load-the-qt-xcb-platform, it should be libxcb-cursor-dev for libxcb. I'd imagine it being xcb-cursor-dev for xcb.
