### ISSUE TITLE
Suggestion: More manual sorting options, e.g. color-coding, collections

### ISSUE THREAD

**Issue by FruitClown** [RimSort/RimSort#469]
I'd like the ability to manually sort mods into individual collections, whether it's through color-coding, "collections", or both. This would provide the ability to manage specific mods in bulk, easily find mods of particular types within your own modlists, etc.

**Comment by Xylemm** [comment]
This feature would be immensely helpful for me as well.

**Comment by Limfjorden** [comment]
Mod categorisation is covered in https://github.com/RimSort/RimSort/issues/272 and color-coding is covered in https://github.com/RimSort/RimSort/issues/109

So this issue is a duplicate and should in my opinion be closed.

**Comment by hk21702** [comment]
Both will hopefully be done at some point but require metadata rework to be completed first. Fingers crossed I actually finish it at some point. 

Closing since duplicate. Please continue discussions in relevant issues.
