### ISSUE TITLE
Suggestion: Allow custom SteamCMD path

### ISSUE THREAD

**Issue by jtljac** [RimSort/RimSort#470]
**Is your feature request related to a problem? Please describe.**
RimSort insists on installing it's own copy of SteamCMD, some users may already have an installation of SteamCMD on their system for other purposes, leading to unnecessary extra installations

**Describe the solution you'd like**
An option to set a custom path for an existing install of SteamCMD.

**Comment by hk21702** [comment]
This should already be a thing under Settings > SteamCMD > SteamCMD installation location. You may need to click no to the pop up asking if you want to install it, then set it. Do note that even if you have steam cmd installed already, you may need RimSort to setup the symlink/junction as well, and that process id done through the rimsort steamcmd install process.

**Comment by hk21702** [comment]
Closing since there hasn't been any activity or follow-up information provided for a while. Feel free to reopen otherwise.
