### ISSUE TITLE
FIXME: RimSort crashes when trying to sort mods in a circular dependency

### ISSUE THREAD

**Issue by pancake-creator** [RimSort/RimSort#475]
**Describe the bug:**
RimSort crashes when trying to sort mods in a circular dependency

**To Reproduce:**

1. Move 'Combat Extended', 'Alpha Animals' and 'Pawnmorpher' to the active mods
2. Click on 'Sort'
3. Crash: 'Traceback (most recent call last):
  File "C:\Users\Ciro\Desktop\Mods\RimSort\app\views\main_content_panel.py", line 1205, in _do_sort
  File "C:\Users\Ciro\Desktop\Mods\RimSort\app\sort\topo_sort.py", line 25, in do_topo_sort
  File "C:\Users\Ciro\Desktop\Mods\RimSort\toposort.py", line 83, in toposort
toposort.CircularDependencyError: Circular dependencies exist among these items: {ceteam.combatextended:{'sarg.alphaanimals'}, sarg.alphaanimals:{'tachyonite.pawnmorpherpublic'}, tachyonite.pawnmorpherpublic:{'ceteam.combatextended'}}'

**Expected behavior:**
Sorting mods or a warning message.

**Screenshots:**
![Screenshot 2024-07-08 145241](https://github.com/RimSort/RimSort/assets/175016958/6760fcb5-688c-44f1-9a65-faf516d29a7a)

**Please complete the following information:**

- Operating System: Windows 11
- Processor Architecture: x64
- RimSort version: v1.0.9-edge40+b794f5d
- [RimSort.log](https://github.com/user-attachments/files/16128769/RimSort.log)
- I am running RimSort from a compiled release
- I am using the Topological sort mode

**Checklist before opening issue:**

- I checked the wiki for a solution
- I checked if the issue was already reported (Searched for 'circular dependency' in 'issues', including closed issues)

**Comment by LionelColaso** [comment]
This only haoppens when Community rule is activated You Will have to 
Edit or  Update the community rule using inbuit rule editor
OR
Disable Community rule

**Comment by pancake-creator** [comment]
Thank you I removed the community rule for Alpha Animals and it works
