### ISSUE TITLE
FIXME: Save button flashes when modlist is filtered/searched but not changed.

### ISSUE THREAD

**Issue by jomar0** [RimSort/RimSort#486]
**Describe the bug:**
After saving the active modlist and searching the list, the save button starts flashing as if there are unsaved changes. When clearing the search, the save button continues flashing. Obviously nothing major, but something to look at.

**To Reproduce:**
 1. Save modlist using Save button
 2. Search/filter the modlist

**Expected behavior:**
The save button shouldn't flash if there is no change between the staged modlist and the modlist shown in RimSort

- Operating System: [Windows 11]
- Processor Architecture: [x64]
- RimSort version: v1.0.8
- Are you running from the Python interpreter or from a compiled RimSort release? [Compiled]
- If this is a sorting issue, what sort mode are you using?: [Topological]

**Comment by LionelColaso** [comment]
Update to latest Edge 1.0.9 it is already fixed
