### ISSUE TITLE
FIXME: Crash when moving multiple mods from inactive to active

### ISSUE THREAD

**Issue by BrunodaSilvaBelo** [RimSort/RimSort#496]
**Describe the bug:**
When i try to activate all mods the following error occurs:
```
Traceback (most recent call last):
  File "/opt/rimsort/app/views/mods_panel.py", line 1563, in handle_rows_inserted
TypeError: 'NoneType' object is not subscriptable
```
Moving a small number (4-5) each by each don't cause this error.

**To Reproduce:**
1. Have a large number of mods
2. Select all mods
3. Move to active tab
4. Error appears

**Expected behavior:**
Mods is moved to activate

- Operating System: Archlinux
- Processor Architecture: x86
- RimSort version: v1.0.8-1
- Please provide a `RimSort.log`: http://0x0.st/X9cv.old.log
- Are you running from the Python interpreter or from a compiled RimSort release? archlinux aur

**Comment by hk21702** [comment]
This is fixed in the latest edge version.
