### ISSUE TITLE
FIXME: All mods dissapear when clicking the "sort" button multiple times

### ISSUE THREAD

**Issue by Thekiborg** [RimSort/RimSort#51]
OS: Windows 10 Pro 10.0.19045

1. Click the sort button multiple times, in my case, 3 times is enough for all the lists to dissapear
2. After doing that, no mods will be shown in either the inactive or the active lists, and the official expansions won't appear either
![image](https://user-images.githubusercontent.com/91976529/227784116-67f94ab2-8e15-41c3-9a22-441c0b4a23f7.png)
3. Clicking any button that updates the list, such as sort, clear, restore, etc, will make the mods visible again

**Comment by twstagg** [comment]
@oceancabbage i can reproduce on Linux

**Comment by largemoron** [comment]
I also got this while the list was refreshing after deleting local and empty folder UNKNOWN mods.

**Comment by twstagg** [comment]
@largemoron shouldn't happen anymore now that i got rid of delayed refresh thread. The issue with the mods disappearing is still there though

**Comment by Limfjorden** [comment]
Is this still present, or should we close this issue?

**Comment by GitWolf22k** [comment]
Able to reproduce in latest edge (after about 10 clicks or so). However only my active list cleared.
