### ISSUE TITLE
FIXME: Anomaly is auto-enabled

### ISSUE THREAD

**Issue by BalderH** [RimSort/RimSort#556]
When disabling Anomaly in Rimsort and saving the mod list, anomaly is still enabled next time Rimworld is started. The only way to actually disable anomaly is by disabling it in Rimworlds built-in mod manager, and to do this every time after using Rimsort.

**Comment by divineDerivative** [comment]
This is likely the same issue as #306.

**Comment by hk21702** [comment]
Closing since this is a duplicate. Please continue any discussions in #306
