### ISSUE TITLE
FIXME: For some reason the original modules are gone.

### ISSUE THREAD

**Issue by Hans-be** [RimSort/RimSort#563]
![image](https://github.com/user-attachments/assets/0cad685a-12b4-485e-ac81-dbcfd5c2fad7)

**Comment by hk21702** [comment]
They should come back if you just hit refresh a few times, or just reopen RimSort.

**Comment by hk21702** [comment]
Closing this since this is a duplicate of #467. Please continue discussions there.

See previous comment for a temporary workaround to this bug.
