### ISSUE TITLE
Non-standard config path warning

### ISSUE THREAD

**Issue by TetrakoHateThis** [RimSort/RimSort#566]
**Describe the bug:**
Simple: RimSort is not loading mods hosted locally into Rimworld. My specific examples include Fishery, Performance Fish and Perspectives: Buildings (a 1.5 branch on Git). I have a modlist of about 400~ mods and the loading process proceeds perfectly fine and the game is functional so there's no errors in the loading process, simply local mods are being excluded. I've tried moving the Local Mods folder into the Ludeon folder in LocalLow, redirecting the filepath there. I've even set them to be GitHub downloads through the "Add Git Mod" option but still the mods are being skipped. The mods appear fine in RimSort's list however.

**To Reproduce:**
Set up a folder for Local Mods, direct Rimsort to this folder.
Put mods in the folder/download from Git.
Mods appear in the list.
Put them into Active Mods.
Launch Game.
Find that solely the local mods are being skipped from the load.

**Expected behavior:**
For all mods to be loaded, both Steam and Local.

**Screenshots:**
![RimsortIssue](https://github.com/user-attachments/assets/3f3a25e9-edf8-4e7e-b425-aff7de804bfe)

**Please complete the following information:**

- Operating System: Win 10 22H2
- Processor Architecture: Zen-3
- RimSort version: 1.0.9
- Please provide a `RimSort.log`: https://0x0.st/X40c.log
- Are you running from the Python interpreter or from a compiled RimSort release?: Compiled release
- If this is a sorting issue, what sort mode are you using?: Topological

**Additional context:**
Nothing else to say.

**Checklist before opening issue:**

- Did you check the wiki for a solution?: Yes. No solution or indicator towards local mod loading was there.
- Did you make sure this issue wasn't already reported?: Checked, anything that appeared relevant didn't make an impact on my issue.

**Comment by hk21702** [comment]
It seems you are using a non-standard directory for local mods. I.e., not just RimWorld/Mods/... While you can do this, you need to set up your launch arguments such that RimWorld will load from those local mods. As for what launch argument to use, I'm honestly am not entirely sure. As far as I know, RimWorld doesn't document these very well. 

For now though, I'd suggest just sticking to the standard directory structure for local mods.

**Comment by hk21702** [comment]
Adding the accessibility label to this since this seems like an opportunity to warn the user via a dialog when setting up paths.

**Comment by twstagg** [comment]
> It seems you are using a non-standard directory for local mods. I.e., not just RimWorld/Mods/... While you can do this, you need to set up your launch arguments such that RimWorld will load from those local mods. As for what launch argument to use, I'm honestly am not entirely sure. As far as I know, RimWorld doesn't document these very well.
> 
> For now though, I'd suggest just sticking to the standard directory structure for local mods.

@hk21702 I do not believe that such an argument exists. RimWorld loads only the mods which are relative to the Game install's `./Mods` folder. While this is slightly different for MacOS, we account for this during autodetection of the Local mods dir, which is basically generated off of what is detected for the Game install dir.

@TetrakoHateThis After reviewing your log, I think we can make some conclusions. You will need to move that `D:\Mod Managers\RimWorld Manual Mods` folder to `D:\Steam\steamapps\common\RimWorld\Mods` and set your Local mods dir to that directory as well. Because what you are currently doing is not supported by RimWorld itself and as such, RimSort will also not support this.
