### ISSUE TITLE
FIXME: RimSort crashes on sort and RimWorld won't launch

### ISSUE THREAD

**Issue by Liljaxtre** [RimSort/RimSort#572]
**Describe the bug:**
When I press "sort", RimSort crashes with this message :

Traceback (most recent call last):
  File "/Applications/RimSort.app/Contents/MacOS/app/views/main_content_panel.py", line 1155, in _do_sort
  File "/Applications/RimSort.app/Contents/MacOS/app/controllers/sort_controller.py", line 31, in __init__
NotImplementedError: Sort method RimPy not implemented

I use a Macbook M1 since two days back and have never owned a Mac before. At first, RimSort couldn't find any of my files such as DLC or mods so I renamed and replaced all related files until it stopped sending "error messages". Still, the mods can't be sorted.

When I try to launch the game, it either freezes at the first loading-screen or the screen turns black. I've been trying to use RimSort on my old PC and it works perfectly so it really shouldn't be because of any mod. Before I downloaded RimSort, the game launched fine. 

**To Reproduce:**

1. Buy a Mac M1
2. Install RimWorld
3. Install Mods
4. Install RimSort
5. Rearrange every single file in your computer
6. Click "Sort"

**Expected behavior:**
RimSort crashes, saying:

Traceback (most recent call last):
  File "/Applications/RimSort.app/Contents/MacOS/app/views/main_content_panel.py", line 1155, in _do_sort
  File "/Applications/RimSort.app/Contents/MacOS/app/controllers/sort_controller.py", line 31, in __init__
NotImplementedError: Sort method RimPy not implemented

Also, you can't launch RimWorld

**Please complete the following information:**

- Operating System: [M1]
- Processor Architecture: [Arm]
- RimSort version: 1.0.9
- Please provide a     [`RimSort.log`:]https://docs.google.com/document/d/1vwTceONYHB6VZMqIpLsSC4CkmLuRqY17XHTcIAzwUnc/edit?usp=sharing
- Are you running from the Python interpreter or from a compiled RimSort release? - Compiled RimSort release
- If this is a sorting issue, what sort mode are you using?: [Alphabetical/Topological] - Alphabetical

**Comment by hk21702** [comment]
Your settings file is malformed for some reason. Try either resetting it, deleting it, or changing your sort mode to topological.

Out of curiosity, are you upgrading from a previous version of rimsort? If so, do you know what version?

**Comment by Liljaxtre** [comment]
I feel so stupid for not trying it before but changing the sort mode worked! 

This is my first time using RimSort. I previously used RimPy. 

Thankyou for the wise advice, kind internet stranger!
