### ISSUE TITLE
Suggestion: Implement method to sync steamcmd acf file with actually installed steamcmd workshop mods

### ISSUE THREAD

**Issue by hk21702** [RimSort/RimSort#594]
Possible fix for #451

The ACF file is used to determine what steamcmd mods need to be updated by the updater. However, there have been reports of issues with using SteamCMD where deleted mods are redownloaded, and mods aren't able to be downloaded by steamCMD in some cases. Some report that clearing the depotcache fixes it. However others say that only deleting the acf file works.

Currently, if a mod is deleted via rimsort, its just rmtree'd. This leaves the key within the acf file. This may potentially be the cause of the above issues. 

There may be risks of dynamically trying to sync the acf file with metadata detected though. Particularly if watchdog  or metadata parsing ever fails. Thus it may be best to only do the deletion when the mod is deleted via RimSort. This leaves the key behind in the acf if deleting manually, but it may just be safer this way.

**Comment by hk21702** [comment]
May hold off on this until after metadata rework because this would require changes with the metadata controller as well as watchdog #403

**Comment by hk21702** [comment]
Actually, a potential alternative may be to have a separate "master" fake acf database. For RimSort operations that require acf information, we read off of that. Every time steamCMD is ran, we clear the real acf file. After steamCMD is finished, we merge the real acf file, with the fake acf database, where all entries of the real acf file overwrites the fake one. 

In theory, this means that the steamCMD is working with a fresh acf file every time it is ran but we maintain the important data in the acf file that we utilize to determine mod updates. Every time steamCMD writes to the acf file, it is doing something with that mod, either confirming that it is updated, downloading a new copy, or updating it. As such, for the purposes of determining last time touched and time created for updates, it should be perfectly fine to overwrite the master.

**Comment by twstagg** [comment]
This should be addressed by #623
