### ISSUE TITLE
Implement log sharing options

### ISSUE THREAD

**Issue by twstagg** [RimSort/RimSort#61]
- [x] Support uploading RimSort log file
- [x] Support uploading Rimworld log files (Player.log, game log, etc)

**Comment by cylian914** [comment]
Where should it be upload ? Custom website or paste.gg   ?

**Comment by twstagg** [comment]
> Where should it be upload ? Custom website or paste.gg ?

Something that is a bit more open to anonymous pasting. We do not want to utilize gist, which requires Github token to be configured & whitelisted to avoid spam filter, however we do not want something that is temporary, as sometimes it takes time for someone to receive a log. We want something that will retain the information for extended period of time, without sacrificing the anonymity.

**Comment by cylian914** [comment]
A  custom version of http://0x0.st/ without the autodeleate ?

**Comment by twstagg** [comment]
@cylian914 I got the 0x0 stuff done and it uploads RimSort.log now

Would you want to take a look at adding this for RimWorld logs?

**Comment by cylian914** [comment]
ok

**Comment by twstagg** [comment]
this has been completed
