### ISSUE TITLE
[Bug]: Blinking save btn when active list is only modified visually

### ISSUE THREAD

**Issue by hk21702** [RimSort/RimSort#618]
### Release Type

Compiled Windows x86 64-bit

### Version

v1.0.10 edge 51

### Operating System

Win 11

### Describe the bug

Currently, the save btn flashes when filters are changed for the active list (searching mods, changing shown mod types) even when there is no real change to the actual modlist. Additionally, the flashing does not go away until a save action is done, even if the filter actions are undone.

Note: This bug doesn't seem to be 100% consistent. Sometimes it occurs, othertimes the expected behavior occurs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Duplicate Issue Check

- [X] I've checked for duplicate issues

### Wiki/FAQ Check

- [X] I've checked the Wiki for a solution

**Comment by Limfjorden** [comment]
This also goes for enabling/disabling a mod without saving in-between. The button will flash, despite the mod list being identical.

**Comment by twstagg** [comment]
I can't reproduce this issue at all. Can either of you help me?

I tried:

1. Drag mod above where it was previously saved, below
2. Put mod back where it originally was
3. Observed save button stop blinking as intended

I also tried:

1. Drag mod(s) to inactive list
2. Put mod back where it was originally
3. Observed save button stop blinking as intended

**Comment by Limfjorden** [comment]
@twstagg I can try on newest edge tonight. I'm on stable right now. It appears when

- I search for anything and delete the search query
- I change which types of mods are visible using the filter button
- I swap the placement of two mods in active list and swap them back
- I drag a mod from the active list to the inactive list and back in the same spot

I don't observe it when I drag a mod from the inactive list to the active list and back
