### ISSUE TITLE
[Bug]: Adding git mod replaces all local mod files if tail of the url is empty

### ISSUE THREAD

**Issue by Puat-MY** [RimSort/RimSort#619]
### Release Type

Compiled Windows x86 64-bit

### Version

RimSort v1.0.9

### Operating System

Windows 10

### Relevant logs

https://0x0.st/XY8n.log

### Describe the bug

1. Select "Download" at ribbon.
2. From dropdown menu, choose "Browse Workshop"
3. Select any mod from Steam Workshop and download via steamcmd.
4. Refresh RimSort, the downloaded mod should show under Inactive list.
5. Select "Download" at ribbon.
6. Select "Add Git Mod".
7. Enter this link 
https://github.com/Maruf61/RimWorld-ResearchPal/
and press OK
8. Select "Clone new". Wait for the "Repo retrieved" prompt.
9. Close the prompt and refresh RimSort.
10. Now, all mods become "Invalid item" under Inactive list, including the successfully downloaded steam mods.

### Additional context

Video below shows the reported bug in action

https://github.com/user-attachments/assets/c7f9a69a-f481-47f4-94f8-3e574e181821

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Duplicate Issue Check

- [X] I've checked for duplicate issues

### Wiki/FAQ Check

- [X] I've checked the Wiki for a solution

**Comment by hk21702** [comment]
Do you mind showing me whats inside of your local mods folder? Also give me an example of whats in one of the folders in there.

**Comment by Puat-MY** [comment]
All files under Rimworld/Mods folder were replaced by the Git repository files.
![image](https://github.com/user-attachments/assets/740d92d1-c6fc-4a0f-afef-ba13853d3911)

![image](https://github.com/user-attachments/assets/6778a015-9f98-4e4b-a00b-c2c20ed00487)

![image](https://github.com/user-attachments/assets/8eaf0b31-5257-4956-98de-0ed9de3fb77f)

Files inside these folders are exactly like those in the Git repository.
![image](https://github.com/user-attachments/assets/f740c9c7-2813-4187-8605-71afc84b4385)
![image](https://github.com/user-attachments/assets/119a9bb2-2ffa-4c47-9c9d-d60d6952eab1)

**Comment by hk21702** [comment]
Ok I think I see whats going on.

This is a special case where because your last slash doesn't have anything after it. Right now, I think rimsort tries to get the repo folder name to make by getting the tail of the given url. The tail defined as whatever is after the last `/`. However, when there is nothing there, the path that the clone happens in is just the local mods folder resulting the in the given behavior.

**Comment by Puat-MY** [comment]
"your last slash doesn't have anything after it"

I think this is the reason behind what I have encountered, removing the last `/` in link makes the download success.

https://github.com/user-attachments/assets/0e6e5885-5b3d-4212-a651-48241b2cae34

Screenshot of contents in folder.
![image](https://github.com/user-attachments/assets/77dce6d4-8a37-45d3-8860-95860e5b1b45)
