### ISSUE TITLE
[Bug]: Virus found in executable (most likely false positive but you never know)

### ISSUE THREAD

**Issue by xynerorias** [RimSort/RimSort#622]
### Release Type

Compiled Windows x86 64-bit

### Version

1.0.10-edge49\b010fe5

### Operating System

Windows 11 23H2 (build 22631.4169)

### Describe the bug

Everything works well but today when booting up Windows Defender detected a malware in the executable (and by extent the Lnk files). It's most likely a false positive but wanted to put it to your attention.

I've seen another issue with the _Puwaders.C!ml_ report but this one is different.

**Screenshot :**
![Screenshot 2024-09-24 163830](https://github.com/user-attachments/assets/63c33b07-3937-4caf-96da-d6eb4adaf380)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Duplicate Issue Check

- [X] I've checked for duplicate issues

### Wiki/FAQ Check

- [X] I've checked the Wiki for a solution

**Comment by hk21702** [comment]
Its a false positive that happens every few new releases. Need to submit the file to microsoft and wait a while for them to fix it manually.

https://github.com/RimSort/RimSort/wiki#macos-gatekeeperwindows-defender-tells-me-that-rimsort-is-damagedunsafe-to-run-is-this-true

**Comment by Limfjorden** [comment]
In the future, please check the wiki for answers before opening new issues.
