### ISSUE TITLE
rimsort fails to update/download mods 

### ISSUE THREAD

**Issue by bamboo2341** [RimSort/RimSort#635]
### Release Type

Compiled (Windows x86-64)

### Version

RimSort-v1.0.10-Windows_x86_64

### Operating System

windows 11

### Describe the bug

i'm getting I/O operation failed erros coming from the workshop update feature or whetever i try to download other contents from the workshop lately, i updated rimworld with the latest version that just came out today.

config file location is correct and local mods location is correct, i didn't touched anything other than deleting the old game version and installing the new one plus changing the locations

### Additional context

![Captura de Tela (6)](https://github.com/user-attachments/assets/f953dd6c-aaa3-46f7-a872-9fd06363d752)

### Code of Conduct

I agree to follow this project's Code of Conduct

### Duplicate Issue Check

I've checked for similar issues and didn't find anything

### Wiki/FAQ Check

I've checked the Wiki for a solution and didn't find a solution

**Comment by hk21702** [comment]
Please post the SteamCMD logs. Their location is printed in that window. They are different from the typical RimSort logs.

**Comment by twstagg** [comment]
> Please post the SteamCMD logs. Their location is printed in that window (In your case, "C:\steamcmd\steacmd\logs"). They are different from the typical RimSort logs. At a minimum we'd need the stderr.txt log from there, but if there is anything else relevant please post them as well.
> 
> Also, are you sure you're on v1.0.10? In the screenshot you shared, the version info says that you're on v1.0.8

This could be related to #380, #451

**Comment by twstagg** [comment]
#623 should address this.

**Comment by hk21702** [comment]
@twstagg Could be different. I don't remember #451 and #380 explicitly saying that its IO related in errors. Just download failure. Need to see the actual error logs to be sure though.
