### ISSUE TITLE
Instance name in settings.json incorrect 

### ISSUE THREAD

**Issue by montaropdf** [RimSort/RimSort#656]
### Release Type

Compiled (Ubuntu 24.04)

### Version

v1.0.10

### Operating System

Ubuntu (KDE)

### Describe the bug

When creating a instance, the `name` of the instance is always set to `Default`. This is causing issues/complains, from the application, because the instance `Default` already exists.

Example:
``` json
    "instances": {
        "Default": {
            "name": "Default",
            "game_folder": "/home/roland/.local/share/RimSort/instances/test1/RimWorld",
            "config_folder": "/home/roland/.local/share/RimSort/instances/test1/InstanceData/Config",
            "local_folder": "/home/roland/.local/share/RimSort/instances/test1/RimWorld/Mods",
            "workshop_folder": "/home/roland/.steam/debian-installation/steamapps/workshop/content/294100",
            "run_args": [
                "-logfile",
                "/home/roland/.local/share/RimSort/instances/test1/RimWorld.log",
                "-savedatafolder=/home/roland/.local/share/RimSort/instances/test1/InstanceData"
            ],
            "steamcmd_install_path": "/home/roland/.local/share/RimSort/instances/test1",
            "steam_client_integration": true
        },
        "test1": {
            "name": "Default",
            "game_folder": "/home/roland/.local/share/RimSort/instances/test1/RimWorld",
            "config_folder": "/home/roland/.local/share/RimSort/instances/test1/InstanceData/Config",
            "local_folder": "/home/roland/.local/share/RimSort/instances/test1/RimWorld/Mods",
            "workshop_folder": "/home/roland/.steam/debian-installation/steamapps/workshop/content/294100",
            "run_args": [
                "-logfile",
                "/home/roland/.local/share/RimSort/instances/test1/RimWorld.log",
                "-savedatafolder=/home/roland/.local/share/RimSort/instances/test1/InstanceData"
            ],
            "steamcmd_install_path": "/home/roland/.local/share/RimSort/instances/test1",
            "steam_client_integration": true
        }
    }
```

### Code of Conduct

I agree to follow this project's Code of Conduct

### Duplicate Issue Check

I've checked for similar issues and didn't find anything

### Wiki/FAQ Check

I've checked the Wiki for a solution and didn't find a solution

**Comment by hk21702** [comment]
I can't replicate this. Just to confirm, you're making the instance by using the drop down menu from the main menu bar and then setting your instance name in the popup?

Also, please include your RimSort logs.

**Comment by montaropdf** [comment]
I used the Clone instance... functionality.

Find below the requested log file.
[RimSort.tar.gz](https://github.com/user-attachments/files/17445670/RimSort.tar.gz)

Trying it again does not trigger the reported issue. Maybe I create the instance with an older version or some other bug modify that data.
