### ISSUE TITLE
Currently active instance name should be displayed in the title bar along side the application name

### ISSUE THREAD

**Issue by montaropdf** [RimSort/RimSort#658]
### Suggestion/proposed solution?

It would be helpful if the name of the currently active instance is displayed in the title bar of the main window alongside the application title.

### Code of Conduct

I agree to follow this project's Code of Conduct

### Duplicate Issue Check

I've checked for similar issues and didn't find anything

### Wiki/FAQ Check

I've checked the Wiki for a solution and didn't find a solution

**Comment by Patryk-Malinowski** [comment]
What type of format would be the most appropriate?

![image](https://github.com/user-attachments/assets/c2c731fb-7851-47ad-8635-623bf05bdc74)
![image](https://github.com/user-attachments/assets/1aad4fdb-a3d9-4200-866a-a03ab1cb3fb9)
![image](https://github.com/user-attachments/assets/01676a84-19b5-4e89-9b7b-1fd79d7a5c5e)
![image](https://github.com/user-attachments/assets/477d4392-f292-43ba-9b2e-212e48eaaf9e)
![image](https://github.com/user-attachments/assets/518dc6cd-78c8-4f23-8c2d-0241f4342d72)

etc...

Feel free to suggest something different from what I have shown too, no matter how small of a difference it is. And if you want I can put in a snapshot of the suggestion so you can see what it would actually look like.

**Comment by Limfjorden** [comment]
I think the first format is the best, because it mimics natural language. 

For the separator, I suggest `:` or `-`.

**Comment by montaropdf** [comment]
Format 1 and 2 are good to me. As for the separator, I do suggest `>` or `|` (pipe), I find them more visible and carry better the fact that the displayed instance is the current context of the program.

**Comment by Patryk-Malinowski** [comment]
> Format 1 and 2 are good to me. As for the separator, I do suggest `>` or `|` (pipe), I find them more visible and carry better the fact that the displayed instance is the current context of the program.

The PR got merged using ':' as the seperator.

I might message in the discord to see what the others think too, and we could change it if needed.

**Comment by montaropdf** [comment]
> > Format 1 and 2 are good to me. As for the separator, I do suggest `>` or `|` (pipe), I find them more visible and carry better the fact that the displayed instance is the current context of the program.
> 
> The PR got merged using ':' as the seperator.
> 
> I might message in the discord to see what the others think too, and we could change it if needed.

Ok, thank you.
