### ISSUE TITLE
Latest Edge CTD

### ISSUE THREAD

**Issue by GitWolf22k** [RimSort/RimSort#663]
### Release Type

Compiled (Windows x86-64)

### Version

v1.0.11-edge7+

### Operating System

Win 10

### Relevant logs

https://0x0.st/XUP9.log

### Describe the bug

CTD when sort button used after modlist reduction by 50%. App will not open unless settings.json is deleted.

### Code of Conduct

I agree to follow this project's Code of Conduct

### Duplicate Issue Check

I've checked for similar issues and didn't find anything

### Wiki/FAQ Check

I've checked the Wiki for a solution and didn't find a solution

**Comment by hk21702** [comment]
I believe this is an issue caused when upgrading from a prior edge release. The steamcmd_auto_clear_depot_cache was introduced earlier, but then moved to be an instance setting. Thus, if you had a settings file that had steamcmd_auto_clear_depot_cache set, but not under the edge7 schema of being an instance setting, then you get a crash.

**Comment by hk21702** [comment]
Weirdly, I can't replicate this issue. Based on the logs, there is a crash when loading the settings file if it contains an unrecognized entry. However, the existing code should already have a mitigation for this. Additionally, I can't replicate this crash if I try to mess with my own settings file, the mitigation seems to work. This is both with the compiled edge release, and running from interpreter at head of main.

@GitWolf22k do you happen to have your old settings file still? If so, do you mind uploading it? You are welcome to edit out any identifying info in it.

**Comment by GitWolf22k** [comment]
Sure. Here tis.
[settings.json](https://github.com/user-attachments/files/17502918/settings.json)

**Comment by hk21702** [comment]
Unfortunately, I still can't replicate the crash. Will leave the issue open for now in case something new happens
