### ISSUE TITLE
Dismiss Error [Suggestion]

### ISSUE THREAD

**Issue by TaelFayre** [RimSort/RimSort#69]
Would it be possible to implement a "ignore error" to a mod, like how Mod Organizer 2 has it, you simply mark an error in a mod on the list to be ignored, if a new error from that mod appears then the error shows up.
I've been currently having 2 errors that are kinda useless so they're pretty annoying, one is from Backstories+ having an HAR requirement(even tho that requirement is for older versions of the game so its useless to me) and World Map Enhanced has mismatched version, but its a visual mod and it runs fine on newer versions of the game

**Comment by twstagg** [comment]
Cylian completed this in #114
