### ISSUE TITLE
FIXME Ensure compatibility with older versions of MacOS

### ISSUE THREAD

**Issue by Limfjorden** [RimSort/RimSort#91]
Hello.

I downloaded the app but the app would not open. After sifting through the logs, I found out that it is built for MacOS 11. Is there a version of the app that is Mojave compatible?

**Comment by twstagg** [comment]
> Hello.
> 
> I downloaded the app but the app would not open. After sifting through the logs, I found out that it is built for MacOS 11. Is there a version of the app that is Mojave compatible?

Hey, Limfjorden!

Sorry to hear you are having issues. I build the i386 Mac releases in a QEMU VM running MacOS Ventura 13.3.1 - at some point I can try to setup a Mojave VM and do a build and do some testing. Likely the issue with current build is that it was built on too new of an OS for that backward compatibility.

If you have some time, would you mind trying to build yourself on your system? Please reference the [Development Guide](https://github.com/RimSort/RimSort/wiki/Development-Guide)

Feel free to ask any questions if needed. I'll let you know if/when i get around to my own testing.

**Comment by Limfjorden** [comment]
I'll try building it, I'll let you know how it goes:)

**Comment by twstagg** [comment]
> I'll try building it, I'll let you know how it goes:)
> 
> EDIT: I have now downloaded Xcode command line tools and python, the first from Apple's website, the latter through homebrew. Do I need to install Xcode as a whole? The guide for building SteamworksPy from source seems to indicate that.

You should actually be able to skip building SteamworksPy, as long as the compiled version (.dylib) I provide in repo works with MacOS Mojave... xD

You do not need the full suite of XCode, only the XCode commandline tools to do so either way.

Do you have Discord? Feel free to add me there if you'd like to chat, I can walk you through it: twsta#3977

**Comment by twstagg** [comment]
@Limfjorden MacOS i386 builds are now being done on Mojave - can you test the Edge release?

https://github.com/RimSort/RimSort/releases/tag/Edge

**Comment by Limfjorden** [comment]
@twstagg Unfortunately not, as I have upgraded to Ventura (rip PvZ). I would've tested but I just decided to bite the bullet.

**Comment by twstagg** [comment]
@Limfjorden ok no problem. I am able to launch it in Mojave (as well as up to Ventura)

I will be closing this. Let me know if any additional issue
